// Code generated by go generate; DO NOT EDIT.
/***************************************************************
 *
 * Copyright (C) 2024, Pelican Project, Morgridge Institute for Research
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ***************************************************************/

package error_codes

import (
	"fmt"
)

type PelicanError struct {
	errorType string
	exitCode  int
	code      int
	retryable bool
	err       error
}
func NewParameterError(err error) *PelicanError {
	return &PelicanError{
		errorType: "Parameter",
		exitCode: 4,
		code: 100,
		retryable: false,
		err: err,
	}
}
func NewResolutionError(err error) *PelicanError {
	return &PelicanError{
		errorType: "Resolution",
		exitCode: 5,
		code: 200,
		retryable: false,
		err: err,
	}
}
func NewContactError(err error) *PelicanError {
	return &PelicanError{
		errorType: "Contact",
		exitCode: 6,
		code: 300,
		retryable: false,
		err: err,
	}
}
func NewContact_DirectorError(err error) *PelicanError {
	return &PelicanError{
		errorType: "Contact.Director",
		exitCode: 6,
		code: 301,
		retryable: false,
		err: err,
	}
}
func NewContact_CacheError(err error) *PelicanError {
	return &PelicanError{
		errorType: "Contact.Cache",
		exitCode: 11,
		code: 302,
		retryable: true,
		err: err,
	}
}
func NewContact_OriginError(err error) *PelicanError {
	return &PelicanError{
		errorType: "Contact.Origin",
		exitCode: 6,
		code: 303,
		retryable: false,
		err: err,
	}
}
func NewAuthorizationError(err error) *PelicanError {
	return &PelicanError{
		errorType: "Authorization",
		exitCode: 7,
		code: 400,
		retryable: false,
		err: err,
	}
}
func NewSpecificationError(err error) *PelicanError {
	return &PelicanError{
		errorType: "Specification",
		exitCode: 8,
		code: 500,
		retryable: false,
		err: err,
	}
}
func NewSpecification_FileNotFoundError(err error) *PelicanError {
	return &PelicanError{
		errorType: "Specification.FileNotFound",
		exitCode: 8,
		code: 501,
		retryable: false,
		err: err,
	}
}
func NewSpecification_FileNotCreatedError(err error) *PelicanError {
	return &PelicanError{
		errorType: "Specification.FileNotCreated",
		exitCode: 8,
		code: 502,
		retryable: false,
		err: err,
	}
}
func NewTransferError(err error) *PelicanError {
	return &PelicanError{
		errorType: "Transfer",
		exitCode: 9,
		code: 600,
		retryable: true,
		err: err,
	}
}
func NewTransfer_StoppedTransferErrorError(err error) *PelicanError {
	return &PelicanError{
		errorType: "Transfer.StoppedTransferError",
		exitCode: 11,
		code: 601,
		retryable: true,
		err: err,
	}
}
func NewTransfer_SlowTransferErrorError(err error) *PelicanError {
	return &PelicanError{
		errorType: "Transfer.SlowTransferError",
		exitCode: 11,
		code: 602,
		retryable: true,
		err: err,
	}
}

// function that maps the error to the exit code
func (e *PelicanError) ExitCode() int {
	return e.exitCode
}

func (e *PelicanError) Error() string {
	if e.err != nil {
		return fmt.Sprintf("%s Error: Error code %d: %v", e.errorType, e.code, e.err)
	}
	return e.errorType
}

func (e *PelicanError) UnWrap() error {
	return e.err
}

func (e *PelicanError) Wrap(err error) *PelicanError {
	e.err = err
	return e
}
