{
 "title": "Prod Director dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Top 10 Projects",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum by(proj) (xrootd_transfer_bytes{job=\"origin_cache_servers\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Origins Data Received",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(xrootd_server_bytes{job=\"origin_cache_servers\", direction=\"rx\"})",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Origins Data Transferred",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(xrootd_server_bytes{job=\"origin_cache_servers\", direction=\"tx\", server_type=\"Origin\"})",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines / Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"prometheus\"}",
     "legendFormat": "Goroutines"
    },
    {
     "expr": "go_threads{job=\"prometheus\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Running Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Origin/Cache Servers Metric Endpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"origin_cache_servers\", server_type=\"Origin\"} == 0)",
     "legendFormat": "Origins Down"
    },
    {
     "expr": "count(up{job=\"origin_cache_servers\", server_type=\"Origin\"} == 1)",
     "legendFormat": "Origins Up"
    },
    {
     "expr": "count(up{job=\"origin_cache_servers\", server_type=\"Cache\"} == 0)",
     "legendFormat": "Caches Down"
    },
    {
     "expr": "count(up{job=\"origin_cache_servers\", server_type=\"Cache\"} == 1)",
     "legendFormat": "Caches Up"
    }
   ]
  },
  {
   "title": "Director Ad w/ 403 Error",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pelican_director_total_advertisements_received{instance=\"osdf-director.osg-htc.org:443\", job=\"prometheus\", status_code=\"403\"}[15m]) > 0",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Director Ad OK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "increase(pelican_director_total_advertisements_received{instance=\"osdf-director.osg-htc.org:443\", job=\"prometheus\", status_code=\"200\"}[5m])",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redirect Requests (delta over 1m) Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(gin_requests_total{job=\"prometheus\", url=~\"/api/v1.0/director/(object|origin)/.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS (1min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(gin_requests_total{job=\"prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redirect Requests (delta over 1m) by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(code) (increase(gin_requests_total{job=\"prometheus\", url=~\"/api/v1.0/director/(object|origin)/.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS (1min) Redirect Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(gin_requests_total{job=\"prometheus\", url=~\"/api/v1.0/director/(object|origin)/.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests/hour (Redirect)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(gin_requests_total{job=\"prometheus\", url=~\"/api/v1.0/director/(object|origin)/.*\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS (1min) by Redirect Requests by Prefixes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "topk(5, rate(gin_requests_total{job=\"prometheus\", url=~\"/api/v1.0/director/(object|origin)/.*\"}[1m]))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Server IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(xrootd_server_io_total{job=\"origin_cache_servers\"}[5m])",
     "legendFormat": "{{server_type}} {{server_name}}"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(gin_request_duration_seconds_sum{job=\"prometheus\"}[1m])) / sum(rate(gin_request_duration_seconds_count{job=\"prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server IO",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(xrootd_server_io_total{job=\"origin_cache_servers\"}[5m])",
     "legendFormat": "{{server_type}} {{server_name}}"
    }
   ]
  },
  {
   "title": "Origin/Cache Health Status",
   "type": "stat",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pelican_component_health_status{job=\"origin_cache_servers\"} != 3",
     "legendFormat": "{{component}} component at {{server_name}}"
    }
   ]
  },
  {
   "title": "Director File Transfer Test Suite",
   "type": "stat",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(pelican_director_active_ftx_test_suite{job=\"prometheus\"}[15m])",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Total Stats",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pelican_director_stat_total", "legendFormat": "{{server_name}} {{result}}" }
   ]
  },
  {
   "title": "Active Stat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
   "targets": [
    {
     "expr": "pelican_director_stat_active{job=\"prometheus\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Maps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "pelican_director_map_items_total",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "TTL cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    { "expr": "pelican_director_ttl_cache", "legendFormat": "{{name}} {{type}}" }
   ]
  },
  {
   "title": "Origin/Cache Servers Metric Status",
   "type": "state-timeline",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "sort(up{job=\"origin_cache_servers\"})",
     "legendFormat": "[{{server_type}}] {{server_name}}"
    }
   ]
  },
  {
   "title": "Pelican Server Distribution",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "up{job=\"origin_cache_servers\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}