{
 "title": "Origin Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Origin Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Component Status",
   "type": "stat",
   "description": "1: Critical\n2: Warning\n3: OK\n4: Unknown\n\n\"web-ui\":       Web interface\n\"xrootd\"*:      XRootD process\n\"cmsd\"*:        CMSD process\n\"federation\"*:  Advertisement to central service\n\"director\"*:    File transfer test (health test) with the director\n\"topology\":     Data fetch from Topology server\n*: only available at origin and cache servers",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pelican_component_health_status",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "stat",
   "description": "This panel displays the aggregated health status of all Pelican server components. The status is determined based on the most critical condition among the individual components:\n\n\t•\tOK: All components are operating normally.\n\t•\tWarning: At least one component is experiencing issues but none are critical.\n\t•\tError: At least one component is in a critical state.\n\nThis panel provides a high-level overview of the system’s health, allowing you to quickly assess if any action is needed. For detailed information about each component’s status, refer to the “Component Status” panel below.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  pelican_component_health_status == 1\n) * 1 OR max(\n  pelican_component_health_status == 2\n) * 2 OR on()\nsum(\n  pelican_component_health_status == 3\n) * 3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "description": "The transfer rate for individual objects",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(xrootd_transfer_bytes[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Projects by Bytes Accessed",
   "type": "table",
   "description": "This table shows the top 5 projects by Bytes Accessed",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, sum by (proj) (xrootd_transfer_bytes{type!=\"write\", proj!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "piechart",
   "description": "Storage volume usage on the XRootD server",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xrootd_storage_volume_bytes{server_type=\"origin\", ns=\"/patrickbrophy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Memory (MB)",
   "type": "timeseries",
   "description": "Pelican memory usage",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of Pelican",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "avg by (instance) (irate(process_cpu_seconds_total{job=\"prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Bytes Transferred",
   "type": "stat",
   "description": "The total number of bytes XRootD sent/received. Ref: https://xrootd.web.cern.ch/doc/dev57/xrd_monitoring.htm#_Toc138968503 (See link.in and link.out)",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "xrootd_server_bytes_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Advanced", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Threads",
   "type": "stat",
   "description": "Pelican Threads - The number of threads being used by the Pelican process\n\nXRootD Idle Threads - Number of scheduler threads waiting for work\n\nXRootD Running Threads - Number of scheduler threads running",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_threads", "legendFormat": "__auto" },
    { "expr": "xrootd_sched_thread_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "XRootD Byte Transfers",
   "type": "stat",
   "description": "The bytes of transfers for individual object. Ref: https://xrootd.web.cern.ch/doc/dev57/xrd_monitoring.htm#_Toc138968523  (See XrdXrootdMonStatXFR)",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "xrootd_transfer_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Go Routines",
   "type": "stat",
   "description": "Number of goroutines that currently exist.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Server Connections",
   "type": "stat",
   "description": "The total number of server connections ",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xrootd_server_connections_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}