# ***************************************************************
#
#  Copyright (C) 2025, Pelican Project, Morgridge Institute for Research
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you
#  may not use this file except in compliance with the License.  You may
#  obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# ***************************************************************

project_name: pelican
version: 2

release:
  prerelease: true

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - make web-build
builds:
  - &build-pelican
    id: pelican
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "amd64"
      - "arm64"
      - "ppc64le"
    dir: ./cmd
    binary: pelican
    tags:
      - forceposix
    ldflags:
      - &ldflags-metadata
        -X github.com/pelicanplatform/pelican/version.commit={{.Commit}} -X github.com/pelicanplatform/pelican/version.date={{.Date}} -X github.com/pelicanplatform/pelican/version.builtBy=goreleaser -X github.com/pelicanplatform/pelican/version.version={{.Version}}
      - &ldflags-strip-symbols
        -s -w
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: ppc64le
      - goos: darwin
        goarch: ppc64le

  # Build a `pelican` binary that includes debugging symbols.
  - <<: *build-pelican
    id: pelican-debug
    gcflags:
      # From https://go.dev/doc/gdb: Disable inlining of function invocations.
      - all="-N"
    ldflags:
      - *ldflags-metadata

  # Build a second, server binary that enables Lotman. Eventually, we'll
  # also use this to filter which modules are built into the binary.
  - id: pelican-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "amd64"
      - "arm64"
    dir: ./cmd
    binary: pelican-server
    tags:
      - forceposix
      - lotman
    ldflags:
      - *ldflags-metadata
      - *ldflags-strip-symbols

# Goreleaser complains if there's a different number of binaries built for different architectures
# in the same archive. Instead of plopping pelican-server in the same archive as pelican, split the
# builds into separate archives.
archives:
  - id: pelican
    builds:
      - pelican
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: '{{ .ProjectName }}-{{ trimsuffix .Version "-next" }}'
  - id: pelican-server
    builds:
      - pelican-server
    name_template: >-
      {{ .ProjectName }}-server_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: '{{ .ProjectName }}-server-{{ trimsuffix .Version "-next" }}'
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch

nfpms:
  - &package-pelican
    id: pelican
    package_name: pelican
    builds:
      - pelican
    # Note that git tags like v7.0.0-rc.1 will be modified by goreleaser when building
    # rpms to be v7.0.0~rc.1-1. The tilde is a special character in RPM versioning that
    # signifies some version substring should be sorted as less than the rest of the version,
    # so that v7.0.0~rc.1-1 < v7.0.0-1.
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: OSG Consortium
    homepage: https://pelicanplatform.org
    maintainer: Pelican Team <help@pelicanplatform.org>
    description: Command-line copy tool for the Open Science Data Federation
    license: ASL 2.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    release: 1
    section: default
    priority: extra
    scripts:
      preinstall: "scripts/preinstall.sh"
    overrides:
      rpm:
        contents:
          - src: LICENSE
            dst: "/usr/share/doc/{{ .PackageName }}-{{ .Version }}/LICENSE.txt"
            file_info:
              mode: 0644
            type: doc
          - src: README.md
            dst: "/usr/share/doc/{{ .PackageName }}-{{ .Version }}/README.md"
            file_info:
              mode: 0644
            type: doc
          - dst: "/etc/pelican"
            type: dir
            file_info:
              mode: 0755
              owner: root
              group: root
          - dst: "/var/lib/pelican"
            type: dir
            file_info:
              mode: 0755
              owner: pelican
              group: pelican
          - dst: "/var/lib/pelican/monitoring"
            type: dir
            file_info:
              mode: 0755
              owner: pelican
              group: pelican
          - dst: "/var/spool/pelican"
            type: dir
            file_info:
              mode: 0755
              owner: pelican
              group: pelican
        dependencies:
          - "/bin/sh"
          - "/usr/bin/getent"
          - "/usr/sbin/useradd"
          - "/usr/sbin/groupadd"
      deb:
        contents:
          - src: LICENSE
            dst: "/usr/share/doc/{{ .PackageName }}/LICENSE.txt"
            file_info:
              mode: 0644
            type: doc
          - src: README.md
            dst: "/usr/share/doc/{{ .PackageName }}/README.md"
            file_info:
              mode: 0644
            type: doc
          - dst: "/etc/pelican"
            type: dir
            file_info:
              mode: 0755
              owner: root
              group: root
          - dst: "/var/lib/pelican"
            type: dir
            file_info:
              mode: 0755
              owner: pelican
              group: pelican
          - dst: "/var/lib/pelican/monitoring"
            type: dir
            file_info:
              mode: 0755
              owner: pelican
              group: pelican
          - dst: "/var/spool/pelican"
            type: dir
            file_info:
              mode: 0755
              owner: pelican
              group: pelican
        dependencies:
          # provides /bin/sh:
          - "dash"
          # for useradd and groupadd:
          - "passwd"
          # for getent:
          - "libc-bin"
      apk:
        contents:
          - src: LICENSE
            dst: "/usr/share/doc/{{ .PackageName }}/LICENSE.txt"
            file_info:
              mode: 0644
            type: doc
          - src: README.md
            dst: "/usr/share/doc/{{ .PackageName }}/README.md"
            file_info:
              mode: 0644
            type: doc
          - dst: "/etc/pelican"
            type: dir
            file_info:
              mode: 0755
              owner: root
              group: root
          - dst: "/var/lib/pelican"
            type: dir
            file_info:
              mode: 0755
              owner: pelican
              group: pelican
          - dst: "/var/lib/pelican/monitoring"
            type: dir
            file_info:
              mode: 0755
              owner: pelican
              group: pelican
          - dst: "/var/spool/pelican"
            type: dir
            file_info:
              mode: 0755
              owner: pelican
              group: pelican
        scripts:
          preinstall: "scripts/preinstall-alpine.sh"
  # end package pelican

  - <<: *package-pelican
    id: pelican-debug
    package_name: pelican-debug
    builds:
      - pelican-debug
    description: Command-line copy tool for the Open Science Data Federation (includes debug symbols)
    formats:
      - rpm
    provides:
      # brianaydemir 2025-05-15: Because some software, e.g., HTCSS, has
      # a version constraint on `pelican`, we need to include some version
      # here. However, I have found no way to refer to {{ .Version }}.
      - pelican = 7.16.1
  # end package pelican-debug

  - id: pelican-osdf-compat
    package_name: pelican-osdf-compat
    builds: []
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: OSG Consortium
    homepage: https://pelicanplatform.org
    maintainer: Pelican Team <help@pelicanplatform.org>
    description: OSDF compatibility files for Pelican
    license: ASL 2.0
    meta: true
    formats:
      - apk
      - deb
      - rpm
    # bindir: /usr/bin
    release: 1
    section: default
    priority: extra
    scripts:
      postinstall: "scripts/postinstall-plugin.sh"
    dependencies:
      - pelican
    provides:
      ## does not work: {{ .Version }} doesn't get substituted in this list
      # - osdf-client = {{ .Version }}
      # - stashcp = {{ .Version }}
      # - condor-stash-plugin = {{ .Version }}
      - "stashcache-client = 7"
      - "osdf-client = 7"
      - "stashcp = 7"
      - "condor-stash-plugin = 7"
    overrides:
      apk:
        contents:
          - src: "./pelican"
            dst: "/usr/bin/osdf"
            type: symlink
          - src: "./pelican"
            dst: "/usr/bin/stashcp"
            type: symlink
      rpm:
        contents:
          - src: "./pelican"
            dst: "/usr/bin/osdf"
            type: symlink
          - src: "./pelican"
            dst: "/usr/bin/stashcp"
            type: symlink
          - src: "../../bin/pelican"
            dst: "/usr/libexec/condor/stash_plugin"
            type: symlink
          - src: "client/resources/10-stash-plugin.conf"
            dst: "/etc/condor/config.d/10-stash-plugin.conf"
            type: config|noreplace
        replaces:
          - "stashcache-client < 7"
          - "osdf-client < 7"
          - "stashcp < 7"
          - "condor-stash-plugin < 7"
        ## rpm specific syntax:
        ## also does not work: %{version} doesn't get expanded
        # provides:
        #   - "osdf-client = %{version}"
        #   - "stashcp = %{version}"
        #   - "condor-stash-plugin = %{version}"
      deb:
        contents:
          - src: "./pelican"
            dst: "/usr/bin/osdf"
            type: symlink
          - src: "./pelican"
            dst: "/usr/bin/stashcp"
            type: symlink
          - src: "../../bin/pelican"
            dst: "/usr/libexec/condor/stash_plugin"
            type: symlink
          - src: "client/resources/10-stash-plugin.conf"
            dst: "/etc/condor/config.d/10-stash-plugin.conf"
            type: config|noreplace
        # deb has different syntax
        provides:
          - "stashcache-client (= 7)"
          - "osdf-client (= 7)"
          - "stashcp (= 7)"
          - "condor-stash-plugin (= 7)"
        replaces:
          - "stashcache-client (<< 7)"
          - "osdf-client (<< 7)"
          - "stashcp (<< 7)"
          - "condor-stash-plugin (<< 7)"
  # end package pelican-osdf-compat

  - id: pelican-server
    package_name: pelican-server
    builds:
      - pelican-server
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: OSG Consortium
    homepage: https://pelicanplatform.org
    maintainer: Pelican Team <help@pelicanplatform.org>
    description: Server binary, SystemD files and configs for Pelican services
    license: ASL 2.0
    meta: false
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    release: 1
    section: default
    priority: extra
    # dependencies are per-package format
    contents:
      - src: "systemd/pelican-cache.service"
        dst: "/usr/lib/systemd/system/pelican-cache.service"
      - src: "systemd/pelican-origin.service"
        dst: "/usr/lib/systemd/system/pelican-origin.service"
      - src: "systemd/pelican-director.service"
        dst: "/usr/lib/systemd/system/pelican-director.service"
      - src: "systemd/pelican-registry.service"
        dst: "/usr/lib/systemd/system/pelican-registry.service"
      - src: "systemd/pelican-cache.yaml"
        dst: "/etc/pelican/pelican-cache.yaml"
        type: config
      - src: "systemd/pelican-origin.yaml"
        dst: "/etc/pelican/pelican-origin.yaml"
        type: config
      - src: "systemd/pelican-director.yaml"
        dst: "/etc/pelican/pelican-director.yaml"
        type: config
      - src: "systemd/pelican-registry.yaml"
        dst: "/etc/pelican/pelican-registry.yaml"
        type: config
      - src: "systemd/pelican.logrotate"
        dst: "/etc/logrotate.d/pelican"
        type: config|noreplace
      - src: "systemd/examples/10-federation.yaml"
        dst: "/etc/pelican/config.d/10-federation.yaml"
        type: config|noreplace
      - src: "systemd/examples/20-origin-exports.yaml"
        dst: "/etc/pelican/config.d/20-origin-exports.yaml"
        type: config|noreplace
      - src: "systemd/examples/60-origin-multiuser.yaml"
        dst: "/etc/pelican/config.d/60-origin-multiuser.yaml"
        type: config|noreplace
      - src: "systemd/examples/90-debugging.yaml"
        dst: "/etc/pelican/config.d/90-debugging.yaml"
        type: config|noreplace
      - dst: "/etc/pelican/config.d"
        type: "dir"
        file_info:
          owner: root
          group: root
          mode: 0755
      - dst: "/usr/share/pelican/config.d"
        type: "dir"
        file_info:
          owner: root
          group: root
          mode: 0755
      - dst: "/var/log/pelican"
        type: "dir"
        file_info:
          owner: root
          group: root
          mode: 0755
    overrides:
      rpm:
        provides:
          ## {{ .Version }} substitutions do not work in this list
          - "pelican-origin = 7"
          - "pelican-cache = 7"
          - "pelican-registry = 7"
          - "pelican-director = 7"
        dependencies:
          - "pelican >= 7.11.0"
          - "xrootd-server >= 1:5.8.2"
          - "xrootd-scitokens"
          - "xrootd-voms"
      deb:
        provides:
          - "pelican-origin (= 7)"
          - "pelican-cache (= 7)"
          - "pelican-registry (= 7)"
          - "pelican-director (= 7)"
        dependencies:
          - "pelican (>= 7.11.0)"
          - "xrootd-server (>= 5.8.2)"
          - "xrootd-scitokens-plugins"
          - "xrootd-voms-plugins"
  # end package pelican-server
