# ***************************************************************
#
#  Copyright (C) 2024, Pelican Project, Morgridge Institute for Research
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you
#  may not use this file except in compliance with the License.  You may
#  obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# ***************************************************************

project_name: pelican

release:
  prerelease: true
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - make web-build
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "amd64"
      - "arm64"
      - "ppc64le"
    id: "pelican"
    dir: ./cmd
    binary: pelican
    tags:
      - forceposix
    ldflags:
      - -s -w -X github.com/pelicanplatform/pelican/config.commit={{.Commit}} -X github.com/pelicanplatform/pelican/config.date={{.Date}} -X github.com/pelicanplatform/pelican/config.builtBy=goreleaser -X github.com/pelicanplatform/pelican/config.version={{.Version}}
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: ppc64le
      - goos: darwin
        goarch: ppc64le

archives:
  - id: pelican
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: '{{ .ProjectName }}-{{ trimsuffix .Version "-next" }}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

nfpms:
  - package_name: pelican
    builds:
      - pelican
    file_name_template: "{{ .ConventionalFileName }}"
    id: pelican
    vendor: OSG Consortium
    homepage: https://pelicanplatform.org
    maintainer: Pelican Team <help@pelicanplatform.org>
    description: Command-line copy tool for the Open Science Data Federation
    license: ASL 2.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    release: 1
    section: default
    priority: extra
    overrides:
      rpm:
        contents:
          - src: LICENSE
            dst: "/usr/share/doc/{{ .PackageName }}-{{ .Version }}/LICENSE.txt"
            file_info:
              mode: 0644
            type: doc
          - src: README.md
            dst: "/usr/share/doc/{{ .PackageName }}-{{ .Version }}/README.md"
            file_info:
              mode: 0644
            type: doc
          - dst: "/etc/pelican"
            type: dir
            file_info:
              mode: 0755
              owner: root
              group: root
      deb:
        contents:
          - src: LICENSE
            dst: "/usr/share/doc/{{ .PackageName }}/LICENSE.txt"
            file_info:
              mode: 0644
            type: doc
          - src: README.md
            dst: "/usr/share/doc/{{ .PackageName }}/README.md"
            file_info:
              mode: 0644
            type: doc
          - dst: "/etc/pelican"
            type: dir
            file_info:
              mode: 0755
              owner: root
              group: root
      apk:
        contents:
          - src: LICENSE
            dst: "/usr/share/doc/{{ .PackageName }}/LICENSE.txt"
            file_info:
              mode: 0644
            type: doc
          - src: README.md
            dst: "/usr/share/doc/{{ .PackageName }}/README.md"
            file_info:
              mode: 0644
            type: doc
          - dst: "/etc/pelican"
            type: dir
            file_info:
              mode: 0755
              owner: root
              group: root
  # end package pelican

  - package_name: pelican-osdf-compat
    builds: []
    file_name_template: "{{ .ConventionalFileName }}"
    id: pelican-osdf-compat
    vendor: OSG Consortium
    homepage: https://pelicanplatform.org
    maintainer: Pelican Team <help@pelicanplatform.org>
    description: OSDF compatibility files for Pelican
    license: ASL 2.0
    meta: true
    formats:
      - apk
      - deb
      - rpm
    # bindir: /usr/bin
    release: 1
    section: default
    priority: extra
    dependencies:
      - pelican
    provides:
      ## does not work: {{ .Version }} doesn't get substituted in this list
      # - osdf-client = {{ .Version }}
      # - stashcp = {{ .Version }}
      # - condor-stash-plugin = {{ .Version }}
      - "stashcache-client = 7"
      - "osdf-client = 7"
      - "stashcp = 7"
      - "condor-stash-plugin = 7"
    overrides:
      apk:
        contents:
          - src: "./pelican"
            dst: "/usr/bin/osdf"
            type: symlink
          - src: "./pelican"
            dst: "/usr/bin/stashcp"
            type: symlink
      rpm:
        contents:
          - src: "./pelican"
            dst: "/usr/bin/osdf"
            type: symlink
          - src: "./pelican"
            dst: "/usr/bin/stashcp"
            type: symlink
          - src: "../../bin/pelican"
            dst: "/usr/libexec/condor/stash_plugin"
            type: symlink
          - src: "client/resources/10-stash-plugin.conf"
            dst: "/etc/condor/config.d/10-stash-plugin.conf"
            type: config|noreplace
        replaces:
          - "stashcache-client < 7"
          - "osdf-client < 7"
          - "stashcp < 7"
          - "condor-stash-plugin < 7"
        ## rpm specific syntax:
        ## also does not work: %{version} doesn't get expanded
        # provides:
        #   - "osdf-client = %{version}"
        #   - "stashcp = %{version}"
        #   - "condor-stash-plugin = %{version}"
      deb:
        contents:
          - src: "./pelican"
            dst: "/usr/bin/osdf"
            type: symlink
          - src: "./pelican"
            dst: "/usr/bin/stashcp"
            type: symlink
          - src: "../../bin/pelican"
            dst: "/usr/libexec/condor/stash_plugin"
            type: symlink
          - src: "client/resources/10-stash-plugin.conf"
            dst: "/etc/condor/config.d/10-stash-plugin.conf"
            type: config|noreplace
        # deb has different syntax
        provides:
          - "stashcache-client (= 7)"
          - "osdf-client (= 7)"
          - "stashcp (= 7)"
          - "condor-stash-plugin (= 7)"
        replaces:
          - "stashcache-client (<< 7)"
          - "osdf-client (<< 7)"
          - "stashcp (<< 7)"
          - "condor-stash-plugin (<< 7)"
  # end package pelican-osdf-compet

  - package_name: pelican-server
    builds: []
    file_name_template: "{{ .ConventionalFileName }}"
    id: pelican-server
    vendor: OSG Consortium
    homepage: https://pelicanplatform.org
    maintainer: Pelican Team <help@pelicanplatform.org>
    description: SystemD files and configs for Pelican services
    license: ASL 2.0
    meta: true
    formats:
      - deb
      - rpm
    release: 1
    section: default
    priority: extra
    # dependencies are per-package format
    contents:
      - src: "systemd/pelican-cache.service"
        dst: "/usr/lib/systemd/system/pelican-cache.service"
      - src: "systemd/pelican-origin.service"
        dst: "/usr/lib/systemd/system/pelican-origin.service"
      - src: "systemd/pelican-director.service"
        dst: "/usr/lib/systemd/system/pelican-director.service"
      - src: "systemd/pelican-registry.service"
        dst: "/usr/lib/systemd/system/pelican-registry.service"
      - src: "systemd/pelican-cache.yaml"
        dst: "/etc/pelican/pelican-cache.yaml"
        type: config|noreplace
      - src: "systemd/pelican-origin.yaml"
        dst: "/etc/pelican/pelican-origin.yaml"
        type: config|noreplace
      - src: "systemd/pelican-director.yaml"
        dst: "/etc/pelican/pelican-director.yaml"
        type: config|noreplace
      - src: "systemd/pelican-registry.yaml"
        dst: "/etc/pelican/pelican-registry.yaml"
        type: config|noreplace
      - src: "systemd/pelican.logrotate"
        dst: "/etc/logrotate.d/pelican"
        type: config|noreplace
      - dst: "/var/log/pelican"
        type: "dir"
        file_info:
          owner: root
          group: root
          mode: 0700

    overrides:
      rpm:
        provides:
          ## {{ .Version }} substitutions do not work in this list
          - "pelican-origin = 7"
          - "pelican-cache = 7"
          - "pelican-registry = 7"
          - "pelican-director = 7"
        dependencies:
          - "pelican >= 7.4.0"
          - "xrootd-server >= 1:5.6.3"
          - "xrootd-scitokens"
          - "xrootd-voms"
      deb:
        provides:
          - "pelican-origin (= 7)"
          - "pelican-cache (= 7)"
          - "pelican-registry (= 7)"
          - "pelican-director (= 7)"
        dependencies:
          - "pelican (>= 7.4.0)"
          - "xrootd-server (>= 5.6.3)"
          - "xrootd-scitokens-plugins"
          - "xrootd-voms-plugins"
  # end package pelican-server
