// Code generated by go generate; DO NOT EDIT.
package token_utils

type TokenScope string

const (
	
	Pelican_Advertise TokenScope = "pelican.advertise"
	Pelican_DirectorTestReport TokenScope = "pelican.director_test_report"
	Pelican_DirectorServiceDiscovery TokenScope = "pelican.director_service_discovery"
	Pelican_NamespaceDelete TokenScope = "pelican.namespace_delete"
	Monitoring_Scrape TokenScope = "monitoring.scrape"
	Monitoring_Query TokenScope = "monitoring.query"
)

func (s TokenScope) String() string {
	return string(s)
}
