/***************************************************************
 *
 * Copyright (C) 2024, Pelican Project, Morgridge Institute for Research
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ***************************************************************/

package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"unicode"

	"gopkg.in/yaml.v3"
)

type ScopeName struct {
	Raw     string
	Display string
	// UserGrantable marks scopes that can be assigned directly to a
	// user or group via the management UI (CheckAdmin et al consult
	// these via EffectiveScopes). Data-plane scopes (wlcg.*,
	// scitokens.*) and inter-server scopes are intentionally false.
	UserGrantable bool
	// Description is the human-readable explanation pulled from
	// docs/scopes.yaml. Used to drive the management UI's scope
	// picker so admins can see what they're granting.
	Description string
}

var requiredScopeKeys = [3]string{"description", "issuedBy", "acceptedBy"}

func handleCaseConversion(s string) string {
	var camelCase string
	nextCap := true // default as true so we capitalize the first letter

	for _, r := range s {
		if r == '_' || r == '.' {
			nextCap = true
			if r == '.' {
				camelCase += "."
			}
			continue
		}

		if nextCap {
			camelCase += string(unicode.ToUpper(r))
			nextCap = false
		} else {

			camelCase += string(r)
		}
	}

	return camelCase
}

func GenTokenScope() {
	filename, _ := filepath.Abs("../docs/scopes.yaml")
	yamlFile, err := os.Open(filename)
	if err != nil {
		panic(err)
	}
	defer yamlFile.Close()

	decoder := yaml.NewDecoder(yamlFile)

	var values []any

	for {
		var value map[string]any
		if err := decoder.Decode(&value); err != nil {
			if err == io.EOF {
				break
			}
			panic(fmt.Errorf("document decode failed: %w", err))
		}
		values = append(values, value)
	}

	scopes := make([]ScopeName, 0)
	wlcgScopes := make([]ScopeName, 0)
	scitokensScopes := make([]ScopeName, 0)
	lotmanScopes := make([]ScopeName, 0)

	for i := 0; i < len(values); i++ {
		entry := values[i].(map[string]any)

		scopeName, ok := entry["name"].(string)
		if !ok {
			panic(fmt.Sprintf("Scope entry at position %d is missing the name attribute", i))
		}
		for _, keyName := range requiredScopeKeys {
			if _, ok := entry[keyName]; !ok {
				panic(fmt.Sprintf("Parameter entry '%s' is missing required key '%s'",
					scopeName, keyName))
			}
		}
		camelScopeName := handleCaseConversion(scopeName)
		scopeNameInSnake := strings.ReplaceAll(camelScopeName, ".", "_")
		r := []rune(scopeNameInSnake)
		displayName := string(r)
		userGrantable := false
		if v, ok := entry["userGrantable"]; ok {
			if b, ok := v.(bool); ok {
				userGrantable = b
			}
		}
		description := ""
		if v, ok := entry["description"]; ok {
			if s, ok := v.(string); ok {
				description = strings.TrimSpace(s)
			}
		}
		if strings.HasPrefix(scopeName, "wlcg") {
			displayName = strings.TrimSuffix(displayName, ":")
			wlcgScopes = append(wlcgScopes, ScopeName{Raw: strings.TrimPrefix(scopeName, "wlcg."), Display: displayName})
		} else if strings.HasPrefix(scopeName, "scitokens") {
			displayName = strings.TrimSuffix(displayName, ":")
			scitokensScopes = append(scitokensScopes, ScopeName{Raw: strings.TrimPrefix(scopeName, "scitokens."), Display: displayName})
		} else if strings.HasPrefix(scopeName, "lot") {
			lotmanScopes = append(lotmanScopes, ScopeName{Raw: scopeName, Display: displayName})
		} else {
			scopes = append(scopes, ScopeName{
				Raw:           scopeName,
				Display:       displayName,
				UserGrantable: userGrantable,
				Description:   description,
			})
		}
	}

	// Create the file to be generated
	f, err := os.Create("../token_scopes/token_scopes.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	err = tokenTemplate.Execute(f, struct {
		Scopes          []ScopeName
		WlcgScopes      []ScopeName
		ScitokensScopes []ScopeName
		LotmanScopes    []ScopeName
	}{
		Scopes:          scopes,
		WlcgScopes:      wlcgScopes,
		ScitokensScopes: scitokensScopes,
		LotmanScopes:    lotmanScopes,
	})

	if err != nil {
		panic(err)
	}
}

var tokenTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT THIS FILE.
// To make changes to source, see generate/scope_generator.go and docs/scopes.yaml
/***************************************************************
 *
 * Copyright (C) 2025, Pelican Project, Morgridge Institute for Research
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ***************************************************************/

package token_scopes

import (
	"github.com/pkg/errors"
)

type TokenScope string

const (
	{{- range $idx, $scope := .Scopes}}
	{{$scope.Display}} TokenScope = "{{$scope.Raw}}"
	{{- end}}

	// WLCG Scopes
	{{- range $idx, $scope := .WlcgScopes}}
	{{$scope.Display}} TokenScope = "{{$scope.Raw}}"
	{{- end}}

	// Scitokens Scopes
	{{- range $idx, $scope := .ScitokensScopes}}
	{{$scope.Display}} TokenScope = "{{$scope.Raw}}"
	{{- end}}

	// Lotman Scopes
	{{- range $idx, $scope := .LotmanScopes}}
	{{$scope.Display}} TokenScope = "{{$scope.Raw}}"
	{{- end}}
)

func (s TokenScope) String() string {
	return string(s)
}

// Interface that allows us to assign a path to some token scopes, such as "storage.read:/foo/bar"
func (s TokenScope) Path(path string) (TokenScope, error) {
	// Only some of the token scopes can be assigned a path. This list might grow in the future.
	if !(
		{{- range $idx, $scope := .WlcgScopes -}}s == {{$scope.Display}} || {{end}}
		{{- range $idx, $scope := .ScitokensScopes -}}s == {{$scope.Display}} || {{end}}false) { // final "false" is a hack so we don't have to post process the template we generate from
		return "", errors.New("cannot assign path to non-wlcg or non-scitokens2 token scope")
	}

	return TokenScope(s.String() + ":" + path), nil
}

// UserGrantableScopes is the set of scopes the server's management UI
// is allowed to assign directly to a user or group. EffectiveScopes()
// reads from user_scopes / group_scopes rows whose value is in this
// list; anything outside of it is rejected at the API boundary so an
// admin can't accidentally hand out a data-plane (wlcg/scitokens) or
// inter-server scope through the user-management surface.
//
// Values come from docs/scopes.yaml entries with userGrantable: true.
var UserGrantableScopes = []TokenScope{
	{{- range $idx, $scope := .Scopes}}
	{{- if $scope.UserGrantable}}
	{{$scope.Display}},
	{{- end}}
	{{- end}}
}

// IsUserGrantable reports whether the supplied scope can be granted to
// users or groups via the management UI / API. Always false for
// data-plane and inter-server scopes; only the entries in
// UserGrantableScopes return true.
func IsUserGrantable(s TokenScope) bool {
	for _, ok := range UserGrantableScopes {
		if ok == s {
			return true
		}
	}
	return false
}

// scopeDescriptions carries the human-readable explanation pulled
// from docs/scopes.yaml. Populated only for non-data-plane scopes
// (the data scopes are documented elsewhere). Used by the management
// UI to surface "what does this scope imply?" on the picker.
var scopeDescriptions = map[TokenScope]string{
	{{- range $idx, $scope := .Scopes}}
	{{- if $scope.Description}}
	{{$scope.Display}}: ` + "`{{$scope.Description}}`" + `,
	{{- end}}
	{{- end}}
}

// Describe returns the human-readable description of the supplied
// scope, or "" when none is available (data-plane scopes intentionally
// have no entry — they're documented in the WLCG / scitokens specs).
func (s TokenScope) Describe() string {
	return scopeDescriptions[s]
}
`))
