// Code generated by go generate; DO NOT EDIT.
/***************************************************************
 *
 * Copyright (C) 2026, Pelican Project, Morgridge Institute for Research
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ***************************************************************/

package config

import (
	"os"
	"strings"

	"github.com/spf13/viper"

	"github.com/pelicanplatform/pelican/param"
)

// Ensure imports are used.
var (
	_ = os.Getenv
	_ = strings.ReplaceAll
)

// SetParameterDefaults sets all parameter defaults from parameters.yaml in
// topologically-sorted dependency order. Seed values (ConfigBase,
// Server.Hostname, RuntimeDir) must already be set in viper via SetDefault
// before calling this function, as dependent params read them inline.
func SetParameterDefaults(v *viper.Viper, isRoot bool, isOSDF bool) {
	// Cache.BlocksToPrefetch
	v.SetDefault(param.Cache_BlocksToPrefetch.GetName(), 0)
	// Cache.ConcurrencyDegradedThreshold
	v.SetDefault(param.Cache_ConcurrencyDegradedThreshold.GetName(), 90)
	// Cache.DefaultCacheTimeout
	v.SetDefault(param.Cache_DefaultCacheTimeout.GetName(), "9.5s")
	// Cache.DirectorTest
	v.SetDefault(param.Cache_DirectorTest.GetName(), true)
	// Cache.DisableClientX509
	v.SetDefault(param.Cache_DisableClientX509.GetName(), true)
	// Cache.EnableBroker
	v.SetDefault(param.Cache_EnableBroker.GetName(), true)
	// Cache.EnableEvictionMonitoring
	v.SetDefault(param.Cache_EnableEvictionMonitoring.GetName(), true)
	// Cache.EnableLotman
	v.SetDefault(param.Cache_EnableLotman.GetName(), false)
	// Cache.EnableOIDC
	v.SetDefault(param.Cache_EnableOIDC.GetName(), false)
	// Cache.EnablePrefetch
	v.SetDefault(param.Cache_EnablePrefetch.GetName(), true)
	// Cache.EnableSiteLocalMode
	v.SetDefault(param.Cache_EnableSiteLocalMode.GetName(), false)
	// Cache.EnableTLSClientAuth
	v.SetDefault(param.Cache_EnableTLSClientAuth.GetName(), false)
	// Cache.EnableVoms
	v.SetDefault(param.Cache_EnableVoms.GetName(), false)
	// Cache.EvictionMonitoringInterval
	v.SetDefault(param.Cache_EvictionMonitoringInterval.GetName(), "60s")
	// Cache.EvictionMonitoringMaxDepth
	v.SetDefault(param.Cache_EvictionMonitoringMaxDepth.GetName(), 1)
	// Cache.ExportLocation
	v.SetDefault(param.Cache_ExportLocation.GetName(), "/")
	// Cache.FedTokenLocation
	{
		val := "${ConfigBase}/cache-fed-token"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Cache_FedTokenLocation.GetName(), val)
	}
	// Cache.HighWaterMark
	v.SetDefault(param.Cache_HighWaterMark.GetName(), 95)
	// Cache.LowWaterMark
	v.SetDefault(param.Cache_LowWaterMark.GetName(), 90)
	// Cache.MinDirectorRefreshInterval
	v.SetDefault(param.Cache_MinDirectorRefreshInterval.GetName(), "15s")
	// Cache.PermittedNamespaces
	v.SetDefault(param.Cache_PermittedNamespaces.GetName(), []string{})
	// Cache.Port
	v.SetDefault(param.Cache_Port.GetName(), 8442)
	// Cache.RunLocation
	if isRoot {
		v.SetDefault(param.Cache_RunLocation.GetName(), "/run/pelican/xrootd/cache")
	} else {
		{
			val := "$XDG_RUNTIME_DIR/pelican/cache"
			val = strings.ReplaceAll(val, "$XDG_RUNTIME_DIR", os.Getenv("XDG_RUNTIME_DIR"))
			v.SetDefault(param.Cache_RunLocation.GetName(), val)
		}
	}
	// Cache.ClientStatisticsLocation
	{
		val := "${Cache.RunLocation}/xrootd.stats"
		val = strings.ReplaceAll(val, "${Cache.RunLocation}", v.GetString(param.Cache_RunLocation.GetName()))
		v.SetDefault(param.Cache_ClientStatisticsLocation.GetName(), val)
	}
	// Cache.SelfTest
	v.SetDefault(param.Cache_SelfTest.GetName(), true)
	// Cache.SelfTestInterval
	v.SetDefault(param.Cache_SelfTestInterval.GetName(), "15s")
	// Cache.SelfTestMaxAge
	v.SetDefault(param.Cache_SelfTestMaxAge.GetName(), "1h")
	// Cache.StorageLocation
	if isRoot {
		v.SetDefault(param.Cache_StorageLocation.GetName(), "/run/pelican/cache")
	} else {
		{
			val := "$XDG_RUNTIME_DIR/pelican/cache"
			val = strings.ReplaceAll(val, "$XDG_RUNTIME_DIR", os.Getenv("XDG_RUNTIME_DIR"))
			v.SetDefault(param.Cache_StorageLocation.GetName(), val)
		}
	}
	// Cache.DataLocations
	{
		vals := []string{"${Cache.StorageLocation}/data"}
		for i, val := range vals {
			val = strings.ReplaceAll(val, "${Cache.StorageLocation}", v.GetString(param.Cache_StorageLocation.GetName()))
			vals[i] = val
		}
		v.SetDefault(param.Cache_DataLocations.GetName(), vals)
	}
	// Cache.MetaLocations
	{
		vals := []string{"${Cache.StorageLocation}/meta"}
		for i, val := range vals {
			val = strings.ReplaceAll(val, "${Cache.StorageLocation}", v.GetString(param.Cache_StorageLocation.GetName()))
			vals[i] = val
		}
		v.SetDefault(param.Cache_MetaLocations.GetName(), vals)
	}
	// Cache.NamespaceLocation
	{
		val := "${Cache.StorageLocation}/namespace"
		val = strings.ReplaceAll(val, "${Cache.StorageLocation}", v.GetString(param.Cache_StorageLocation.GetName()))
		v.SetDefault(param.Cache_NamespaceLocation.GetName(), val)
	}
	// Cache.Url
	{
		val := "https://${Server.Hostname}:${Cache.Port}"
		val = strings.ReplaceAll(val, "${Server.Hostname}", v.GetString(param.Server_Hostname.GetName()))
		val = strings.ReplaceAll(val, "${Cache.Port}", v.GetString(param.Cache_Port.GetName()))
		v.SetDefault(param.Cache_Url.GetName(), val)
	}
	// Cache.XRootDPrefix
	v.SetDefault(param.Cache_XRootDPrefix.GetName(), "cache")
	// Client.AssumeDirectorServerHeader
	v.SetDefault(param.Client_AssumeDirectorServerHeader.GetName(), false)
	// Client.DirectorRetries
	v.SetDefault(param.Client_DirectorRetries.GetName(), 5)
	// Client.DisableHttpProxy
	v.SetDefault(param.Client_DisableHttpProxy.GetName(), false)
	// Client.DisableProxyFallback
	v.SetDefault(param.Client_DisableProxyFallback.GetName(), false)
	// Client.EnableOverwrites
	v.SetDefault(param.Client_EnableOverwrites.GetName(), false)
	// Client.IsPlugin
	v.SetDefault(param.Client_IsPlugin.GetName(), false)
	// Client.MaximumDownloadSpeed
	v.SetDefault(param.Client_MaximumDownloadSpeed.GetName(), 0)
	// Client.MinimumDownloadSpeed
	v.SetDefault(param.Client_MinimumDownloadSpeed.GetName(), 102400)
	// Client.SlowTransferRampupTime
	v.SetDefault(param.Client_SlowTransferRampupTime.GetName(), "100s")
	// Client.SlowTransferWindow
	v.SetDefault(param.Client_SlowTransferWindow.GetName(), "30s")
	// Client.StoppedTransferTimeout
	v.SetDefault(param.Client_StoppedTransferTimeout.GetName(), "100s")
	// Client.WorkerCount
	v.SetDefault(param.Client_WorkerCount.GetName(), 5)
	// ClientAgent.HistoryRetentionDays
	v.SetDefault(param.ClientAgent_HistoryRetentionDays.GetName(), 30)
	// ClientAgent.IdleTimeout
	v.SetDefault(param.ClientAgent_IdleTimeout.GetName(), "10m")
	// ClientAgent.MaxConcurrentJobs
	v.SetDefault(param.ClientAgent_MaxConcurrentJobs.GetName(), 5)
	// ClientAgent.ProgressUpdateInterval
	v.SetDefault(param.ClientAgent_ProgressUpdateInterval.GetName(), "5s")
	// ConfigLocations
	v.SetDefault(param.ConfigLocations.GetName(), []string{})
	// Director.AdaptiveSortEWMATimeConstant
	v.SetDefault(param.Director_AdaptiveSortEWMATimeConstant.GetName(), "5m")
	// Director.AdaptiveSortTruncateConstant
	v.SetDefault(param.Director_AdaptiveSortTruncateConstant.GetName(), 6)
	// Director.AdvertisementTTL
	v.SetDefault(param.Director_AdvertisementTTL.GetName(), "15m")
	// Director.AssumePresenceAtSingleOrigin
	v.SetDefault(param.Director_AssumePresenceAtSingleOrigin.GetName(), true)
	// Director.CachePresenceCapacity
	v.SetDefault(param.Director_CachePresenceCapacity.GetName(), 2000)
	// Director.CachePresenceTTL
	v.SetDefault(param.Director_CachePresenceTTL.GetName(), "1m")
	// Director.CacheResponseHostnames
	v.SetDefault(param.Director_CacheResponseHostnames.GetName(), []string{})
	// Director.CacheSortMethod
	v.SetDefault(param.Director_CacheSortMethod.GetName(), "distance")
	// Director.CachesPullFromCaches
	v.SetDefault(param.Director_CachesPullFromCaches.GetName(), false)
	// Director.CheckCachePresence
	v.SetDefault(param.Director_CheckCachePresence.GetName(), true)
	// Director.CheckOriginPresence
	v.SetDefault(param.Director_CheckOriginPresence.GetName(), true)
	// Director.DefaultResponse
	v.SetDefault(param.Director_DefaultResponse.GetName(), "cache")
	// Director.EnableBroker
	v.SetDefault(param.Director_EnableBroker.GetName(), true)
	// Director.EnableFederationMetadataHosting
	v.SetDefault(param.Director_EnableFederationMetadataHosting.GetName(), true)
	// Director.EnableOIDC
	v.SetDefault(param.Director_EnableOIDC.GetName(), false)
	// Director.FedTokenLifetime
	v.SetDefault(param.Director_FedTokenLifetime.GetName(), "15m")
	// Director.FilterCachesInErrorState
	v.SetDefault(param.Director_FilterCachesInErrorState.GetName(), true)
	// Director.FilteredServers
	v.SetDefault(param.Director_FilteredServers.GetName(), []string{})
	// Director.GeoIPLocation
	if isRoot {
		v.SetDefault(param.Director_GeoIPLocation.GetName(), "/var/cache/pelican/maxmind/GeoLite2-City.mmdb")
	} else {
		{
			val := "${ConfigBase}/maxmind/GeoLite2-city.mmdb"
			val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
			v.SetDefault(param.Director_GeoIPLocation.GetName(), val)
		}
	}
	// Director.MaxStatResponse
	v.SetDefault(param.Director_MaxStatResponse.GetName(), 1)
	// Director.MetadataComparisonInterval
	v.SetDefault(param.Director_MetadataComparisonInterval.GetName(), "10m")
	// Director.MinStatResponse
	v.SetDefault(param.Director_MinStatResponse.GetName(), 1)
	// Director.OriginCacheHealthTestInterval
	v.SetDefault(param.Director_OriginCacheHealthTestInterval.GetName(), "15s")
	// Director.OriginResponseHostnames
	v.SetDefault(param.Director_OriginResponseHostnames.GetName(), []string{})
	// Director.RegistryQueryInterval
	v.SetDefault(param.Director_RegistryQueryInterval.GetName(), "1m")
	// Director.StatConcurrencyLimit
	v.SetDefault(param.Director_StatConcurrencyLimit.GetName(), 100)
	// Director.StatTimeout
	v.SetDefault(param.Director_StatTimeout.GetName(), "2000ms")
	// Federation.DiscoveryUrl
	if isOSDF {
		v.SetDefault(param.Federation_DiscoveryUrl.GetName(), "https://osg-htc.org")
	}
	// Federation.TopologyDowntimeUrl
	if isOSDF {
		v.SetDefault(param.Federation_TopologyDowntimeUrl.GetName(), "https://topology.opensciencegrid.org/rgdowntime/xml")
	}
	// Federation.TopologyNamespaceUrl
	if isOSDF {
		v.SetDefault(param.Federation_TopologyNamespaceUrl.GetName(), "https://topology.opensciencegrid.org/osdf/namespaces?production=1")
	}
	// Federation.TopologyReloadInterval
	if isOSDF {
		v.SetDefault(param.Federation_TopologyReloadInterval.GetName(), "4.5m")
	}
	// Federation.TopologyUrl
	if isOSDF {
		v.SetDefault(param.Federation_TopologyUrl.GetName(), "https://topology.opensciencegrid.org")
	}
	// Issuer.AuthenticationSource
	v.SetDefault(param.Issuer_AuthenticationSource.GetName(), "OIDC")
	// Issuer.DynamicClientStaleTimeout
	v.SetDefault(param.Issuer_DynamicClientStaleTimeout.GetName(), "336h")
	// Issuer.DynamicClientUnusedTimeout
	v.SetDefault(param.Issuer_DynamicClientUnusedTimeout.GetName(), "1h")
	// Issuer.GroupRequirements
	v.SetDefault(param.Issuer_GroupRequirements.GetName(), []string{})
	// Issuer.OIDCAuthenticationUserClaim
	v.SetDefault(param.Issuer_OIDCAuthenticationUserClaim.GetName(), "sub")
	// Issuer.OIDCGroupClaim
	v.SetDefault(param.Issuer_OIDCGroupClaim.GetName(), "groups")
	// Issuer.OIDCIssuerClaim
	v.SetDefault(param.Issuer_OIDCIssuerClaim.GetName(), "iss")
	// Issuer.OIDCPreferClaimsFromIDToken
	v.SetDefault(param.Issuer_OIDCPreferClaimsFromIDToken.GetName(), false)
	// Issuer.OIDCSubjectClaim
	v.SetDefault(param.Issuer_OIDCSubjectClaim.GetName(), "sub")
	// Issuer.PublicClientID
	v.SetDefault(param.Issuer_PublicClientID.GetName(), "pelican-public-client")
	// Issuer.QDLLocation
	v.SetDefault(param.Issuer_QDLLocation.GetName(), "/opt/qdl")
	// Issuer.RedirectUris
	if isRoot {
		v.SetDefault(param.Issuer_RedirectUris.GetName(), []string{})
	} else {
		v.SetDefault(param.Issuer_RedirectUris.GetName(), []string{})
	}
	// Issuer.RefreshTokenGracePeriod
	v.SetDefault(param.Issuer_RefreshTokenGracePeriod.GetName(), "5m")
	// Issuer.ScitokensServerLocation
	v.SetDefault(param.Issuer_ScitokensServerLocation.GetName(), "/opt/scitokens-server")
	// Issuer.TomcatLocation
	v.SetDefault(param.Issuer_TomcatLocation.GetName(), "/opt/tomcat")
	// Issuer.UserStripDomain
	v.SetDefault(param.Issuer_UserStripDomain.GetName(), false)
	// IssuerKeysDirectory
	{
		val := "${ConfigBase}/issuer-keys"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.IssuerKeysDirectory.GetName(), val)
	}
	// LocalCache.HighWaterMarkPercentage
	v.SetDefault(param.LocalCache_HighWaterMarkPercentage.GetName(), 95)
	// LocalCache.LowWaterMarkPercentage
	v.SetDefault(param.LocalCache_LowWaterMarkPercentage.GetName(), 85)
	// LocalCache.RunLocation
	if isRoot {
		v.SetDefault(param.LocalCache_RunLocation.GetName(), "/run/pelican/localcache")
	} else {
		{
			val := "$XDG_RUNTIME_DIR/pelican/localcache"
			val = strings.ReplaceAll(val, "$XDG_RUNTIME_DIR", os.Getenv("XDG_RUNTIME_DIR"))
			v.SetDefault(param.LocalCache_RunLocation.GetName(), val)
		}
	}
	// LocalCache.DataLocation
	{
		val := "${LocalCache.RunLocation}/cache"
		val = strings.ReplaceAll(val, "${LocalCache.RunLocation}", v.GetString(param.LocalCache_RunLocation.GetName()))
		v.SetDefault(param.LocalCache_DataLocation.GetName(), val)
	}
	// LocalCache.Size
	v.SetDefault(param.LocalCache_Size.GetName(), 0)
	// LocalCache.Socket
	{
		val := "${LocalCache.RunLocation}/cache.sock"
		val = strings.ReplaceAll(val, "${LocalCache.RunLocation}", v.GetString(param.LocalCache_RunLocation.GetName()))
		v.SetDefault(param.LocalCache_Socket.GetName(), val)
	}
	// Logging.Cache.Http
	v.SetDefault(param.Logging_Cache_Http.GetName(), "error")
	// Logging.Cache.Lotman
	v.SetDefault(param.Logging_Cache_Lotman.GetName(), "error")
	// Logging.Cache.Ofs
	v.SetDefault(param.Logging_Cache_Ofs.GetName(), "error")
	// Logging.Cache.Pfc
	v.SetDefault(param.Logging_Cache_Pfc.GetName(), "info")
	// Logging.Cache.Pss
	v.SetDefault(param.Logging_Cache_Pss.GetName(), "error")
	// Logging.Cache.PssSetOpt
	v.SetDefault(param.Logging_Cache_PssSetOpt.GetName(), "error")
	// Logging.Cache.Scitokens
	v.SetDefault(param.Logging_Cache_Scitokens.GetName(), "fatal")
	// Logging.Cache.Xrd
	v.SetDefault(param.Logging_Cache_Xrd.GetName(), "error")
	// Logging.Cache.Xrootd
	v.SetDefault(param.Logging_Cache_Xrootd.GetName(), "error")
	// Logging.Client.ProgressInterval
	v.SetDefault(param.Logging_Client_ProgressInterval.GetName(), "1m")
	// Logging.DisableProgressBars
	v.SetDefault(param.Logging_DisableProgressBars.GetName(), false)
	// Logging.Origin.Cms
	v.SetDefault(param.Logging_Origin_Cms.GetName(), "error")
	// Logging.Origin.Http
	v.SetDefault(param.Logging_Origin_Http.GetName(), "error")
	// Logging.Origin.Ofs
	v.SetDefault(param.Logging_Origin_Ofs.GetName(), "error")
	// Logging.Origin.Oss
	v.SetDefault(param.Logging_Origin_Oss.GetName(), "error")
	// Logging.Origin.Scitokens
	v.SetDefault(param.Logging_Origin_Scitokens.GetName(), "fatal")
	// Logging.Origin.Xrd
	v.SetDefault(param.Logging_Origin_Xrd.GetName(), "error")
	// Logging.Origin.Xrootd
	v.SetDefault(param.Logging_Origin_Xrootd.GetName(), "info")
	// Lotman.DefaultLotDeletionLifetime
	v.SetDefault(param.Lotman_DefaultLotDeletionLifetime.GetName(), "4032h")
	// Lotman.DefaultLotExpirationLifetime
	v.SetDefault(param.Lotman_DefaultLotExpirationLifetime.GetName(), "2016h")
	// Lotman.EnableAPI
	v.SetDefault(param.Lotman_EnableAPI.GetName(), false)
	// Lotman.EnabledPolicy
	v.SetDefault(param.Lotman_EnabledPolicy.GetName(), "fairshare")
	// Lotman.LotHome
	if isRoot {
		v.SetDefault(param.Lotman_LotHome.GetName(), "/var/lib/lotman")
	} else {
		{
			val := "${ConfigBase}"
			val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
			v.SetDefault(param.Lotman_LotHome.GetName(), val)
		}
	}
	// Monitoring.AggregatePrefixes
	v.SetDefault(param.Monitoring_AggregatePrefixes.GetName(), []string{"/*"})
	// Monitoring.DataLocation
	if isRoot {
		v.SetDefault(param.Monitoring_DataLocation.GetName(), "/var/lib/pelican/monitoring/data")
	} else {
		{
			val := "${ConfigBase}/monitoring/data"
			val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
			v.SetDefault(param.Monitoring_DataLocation.GetName(), val)
		}
	}
	// Monitoring.DataRetention
	v.SetDefault(param.Monitoring_DataRetention.GetName(), "360h")
	// Monitoring.DataRetentionSize
	v.SetDefault(param.Monitoring_DataRetentionSize.GetName(), "0B")
	// Monitoring.EnablePrometheus
	v.SetDefault(param.Monitoring_EnablePrometheus.GetName(), true)
	// Monitoring.LabelLimit
	v.SetDefault(param.Monitoring_LabelLimit.GetName(), 64)
	// Monitoring.LabelNameLengthLimit
	v.SetDefault(param.Monitoring_LabelNameLengthLimit.GetName(), 128)
	// Monitoring.LabelValueLengthLimit
	v.SetDefault(param.Monitoring_LabelValueLengthLimit.GetName(), 2048)
	// Monitoring.MetricAuthorization
	v.SetDefault(param.Monitoring_MetricAuthorization.GetName(), true)
	// Monitoring.PortHigher
	v.SetDefault(param.Monitoring_PortHigher.GetName(), 9999)
	// Monitoring.PortLower
	v.SetDefault(param.Monitoring_PortLower.GetName(), 9930)
	// Monitoring.PromQLAuthorization
	v.SetDefault(param.Monitoring_PromQLAuthorization.GetName(), true)
	// Monitoring.SampleLimit
	v.SetDefault(param.Monitoring_SampleLimit.GetName(), 200)
	// Monitoring.StorageCriticalThreshold
	v.SetDefault(param.Monitoring_StorageCriticalThreshold.GetName(), 90)
	// Monitoring.StorageHealthCheckInterval
	v.SetDefault(param.Monitoring_StorageHealthCheckInterval.GetName(), "5m")
	// Monitoring.StorageWarningThreshold
	v.SetDefault(param.Monitoring_StorageWarningThreshold.GetName(), 80)
	// Monitoring.TokenExpiresIn
	v.SetDefault(param.Monitoring_TokenExpiresIn.GetName(), "1h")
	// Monitoring.TokenRefreshInterval
	v.SetDefault(param.Monitoring_TokenRefreshInterval.GetName(), "5m")
	// OIDC.AuthorizationEndpoint
	v.SetDefault(param.OIDC_AuthorizationEndpoint.GetName(), "https://cilogon.org/authorize")
	// OIDC.ClientIDFile
	{
		val := "${ConfigBase}/oidc-client-id"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.OIDC_ClientIDFile.GetName(), val)
	}
	// OIDC.ClientSecretFile
	{
		val := "${ConfigBase}/oidc-client-secret"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.OIDC_ClientSecretFile.GetName(), val)
	}
	// OIDC.DeviceAuthEndpoint
	v.SetDefault(param.OIDC_DeviceAuthEndpoint.GetName(), "https://cilogon.org/oauth2/device_authorization")
	// OIDC.Issuer
	v.SetDefault(param.OIDC_Issuer.GetName(), "https://cilogon.org")
	// OIDC.Scopes
	v.SetDefault(param.OIDC_Scopes.GetName(), []string{"openid", "email", "profile"})
	// OIDC.TokenEndpoint
	v.SetDefault(param.OIDC_TokenEndpoint.GetName(), "https://cilogon.org/oauth2/token")
	// OIDC.UserInfoEndpoint
	v.SetDefault(param.OIDC_UserInfoEndpoint.GetName(), "https://cilogon.org/oauth2/userinfo")
	// Origin.ConcurrencyDegradedThreshold
	v.SetDefault(param.Origin_ConcurrencyDegradedThreshold.GetName(), 90)
	// Origin.DbLocation
	if isRoot {
		v.SetDefault(param.Origin_DbLocation.GetName(), "/var/lib/pelican/origin.sqlite")
	} else {
		{
			val := "${ConfigBase}/origin.sqlite"
			val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
			v.SetDefault(param.Origin_DbLocation.GetName(), val)
		}
	}
	// Origin.DefaultChecksumTypes
	v.SetDefault(param.Origin_DefaultChecksumTypes.GetName(), []string{"crc32c"})
	// Origin.DirectorTest
	v.SetDefault(param.Origin_DirectorTest.GetName(), true)
	// Origin.DisableDirectClients
	v.SetDefault(param.Origin_DisableDirectClients.GetName(), false)
	// Origin.DiskUsageCalculationDelay
	v.SetDefault(param.Origin_DiskUsageCalculationDelay.GetName(), "5m")
	// Origin.DiskUsageCalculationInterval
	v.SetDefault(param.Origin_DiskUsageCalculationInterval.GetName(), "24h")
	// Origin.DiskUsageCalculationRateLimit
	v.SetDefault(param.Origin_DiskUsageCalculationRateLimit.GetName(), 1000)
	// Origin.EnableAtomicUploads
	v.SetDefault(param.Origin_EnableAtomicUploads.GetName(), false)
	// Origin.EnableBroker
	v.SetDefault(param.Origin_EnableBroker.GetName(), false)
	// Origin.EnableCmsd
	v.SetDefault(param.Origin_EnableCmsd.GetName(), true)
	// Origin.EnableDirectReads
	v.SetDefault(param.Origin_EnableDirectReads.GetName(), true)
	// Origin.EnableDiskUsageCalculation
	v.SetDefault(param.Origin_EnableDiskUsageCalculation.GetName(), false)
	// Origin.EnableIssuer
	v.SetDefault(param.Origin_EnableIssuer.GetName(), false)
	// Origin.EnableListings
	v.SetDefault(param.Origin_EnableListings.GetName(), true)
	// Origin.EnableMacaroons
	v.SetDefault(param.Origin_EnableMacaroons.GetName(), false)
	// Origin.EnableOIDC
	v.SetDefault(param.Origin_EnableOIDC.GetName(), false)
	// Origin.EnablePublicReads
	v.SetDefault(param.Origin_EnablePublicReads.GetName(), false)
	// Origin.EnableReads
	v.SetDefault(param.Origin_EnableReads.GetName(), true)
	// Origin.EnableVoms
	v.SetDefault(param.Origin_EnableVoms.GetName(), true)
	// Origin.EnableWrites
	v.SetDefault(param.Origin_EnableWrites.GetName(), true)
	// Origin.ExportVolumes
	v.SetDefault(param.Origin_ExportVolumes.GetName(), []string{})
	// Origin.FedTokenLocation
	{
		val := "${ConfigBase}/origin-fed-token"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Origin_FedTokenLocation.GetName(), val)
	}
	// Origin.GlobusConfigLocation
	if isRoot {
		v.SetDefault(param.Origin_GlobusConfigLocation.GetName(), "/run/pelican/xrootd/origin/globus")
	} else {
		{
			val := "$XDG_RUNTIME_DIR/pelican/xrootd/origin/globus"
			val = strings.ReplaceAll(val, "$XDG_RUNTIME_DIR", os.Getenv("XDG_RUNTIME_DIR"))
			v.SetDefault(param.Origin_GlobusConfigLocation.GetName(), val)
		}
	}
	// Origin.IssuerMode
	v.SetDefault(param.Origin_IssuerMode.GetName(), "oa4mp")
	// Origin.Multiuser
	if isRoot {
		v.SetDefault(param.Origin_Multiuser.GetName(), true)
	} else {
		v.SetDefault(param.Origin_Multiuser.GetName(), false)
	}
	// Origin.Port
	v.SetDefault(param.Origin_Port.GetName(), 8443)
	// Origin.RunLocation
	if isRoot {
		v.SetDefault(param.Origin_RunLocation.GetName(), "/run/pelican/xrootd/origin")
	} else {
		{
			val := "$XDG_RUNTIME_DIR/pelican/origin"
			val = strings.ReplaceAll(val, "$XDG_RUNTIME_DIR", os.Getenv("XDG_RUNTIME_DIR"))
			v.SetDefault(param.Origin_RunLocation.GetName(), val)
		}
	}
	// Origin.S3UrlStyle
	v.SetDefault(param.Origin_S3UrlStyle.GetName(), "path")
	// Origin.SSH.AuthMethods
	v.SetDefault(param.Origin_SSH_AuthMethods.GetName(), []string{"publickey", "agent", "keyboard-interactive", "password"})
	// Origin.SSH.AutoAddHostKey
	v.SetDefault(param.Origin_SSH_AutoAddHostKey.GetName(), false)
	// Origin.SSH.ChallengeTimeout
	v.SetDefault(param.Origin_SSH_ChallengeTimeout.GetName(), "1m")
	// Origin.SSH.ConnectTimeout
	v.SetDefault(param.Origin_SSH_ConnectTimeout.GetName(), "30s")
	// Origin.SSH.KeepaliveInterval
	v.SetDefault(param.Origin_SSH_KeepaliveInterval.GetName(), "5s")
	// Origin.SSH.KeepaliveTimeout
	v.SetDefault(param.Origin_SSH_KeepaliveTimeout.GetName(), "20s")
	// Origin.SSH.MaxRetries
	v.SetDefault(param.Origin_SSH_MaxRetries.GetName(), 5)
	// Origin.SSH.Port
	v.SetDefault(param.Origin_SSH_Port.GetName(), 22)
	// Origin.SSH.RemotePelicanBinaryOverrides
	v.SetDefault(param.Origin_SSH_RemotePelicanBinaryOverrides.GetName(), []string{})
	// Origin.SSH.SessionEstablishTimeout
	v.SetDefault(param.Origin_SSH_SessionEstablishTimeout.GetName(), "5m")
	// Origin.SSH.TunnelCallback
	v.SetDefault(param.Origin_SSH_TunnelCallback.GetName(), false)
	// Origin.ScitokensGroupsClaim
	v.SetDefault(param.Origin_ScitokensGroupsClaim.GetName(), "wlcg.groups")
	// Origin.ScitokensMapSubject
	v.SetDefault(param.Origin_ScitokensMapSubject.GetName(), false)
	// Origin.ScitokensRestrictedPaths
	v.SetDefault(param.Origin_ScitokensRestrictedPaths.GetName(), []string{})
	// Origin.SelfTest
	v.SetDefault(param.Origin_SelfTest.GetName(), true)
	// Origin.SelfTestInterval
	v.SetDefault(param.Origin_SelfTestInterval.GetName(), "15s")
	// Origin.SelfTestMaxAge
	v.SetDefault(param.Origin_SelfTestMaxAge.GetName(), "1h")
	// Origin.StorageType
	v.SetDefault(param.Origin_StorageType.GetName(), "posix")
	// Origin.SupportedChecksumTypes
	v.SetDefault(param.Origin_SupportedChecksumTypes.GetName(), []string{})
	// Origin.TransferRateLimit
	v.SetDefault(param.Origin_TransferRateLimit.GetName(), "0")
	// Origin.UploadTempLocation
	{
		val := "${Origin.RunLocation}/in-progress"
		val = strings.ReplaceAll(val, "${Origin.RunLocation}", v.GetString(param.Origin_RunLocation.GetName()))
		v.SetDefault(param.Origin_UploadTempLocation.GetName(), val)
	}
	// Origin.Url
	{
		val := "https://${Server.Hostname}:${Origin.Port}"
		val = strings.ReplaceAll(val, "${Server.Hostname}", v.GetString(param.Server_Hostname.GetName()))
		val = strings.ReplaceAll(val, "${Origin.Port}", v.GetString(param.Origin_Port.GetName()))
		v.SetDefault(param.Origin_Url.GetName(), val)
	}
	// Origin.TokenAudience
	{
		val := "${Origin.Url}"
		val = strings.ReplaceAll(val, "${Origin.Url}", v.GetString(param.Origin_Url.GetName()))
		v.SetDefault(param.Origin_TokenAudience.GetName(), val)
	}
	// Origin.UserMapfileRefreshInterval
	v.SetDefault(param.Origin_UserMapfileRefreshInterval.GetName(), "1m")
	// Origin.XRootDPrefix
	v.SetDefault(param.Origin_XRootDPrefix.GetName(), "origin")
	// Plugin.DirectorDecisionPercentage
	v.SetDefault(param.Plugin_DirectorDecisionPercentage.GetName(), 20)
	// Registry.InstitutionsUrlReloadMinutes
	v.SetDefault(param.Registry_InstitutionsUrlReloadMinutes.GetName(), "15m")
	// Registry.RequireCacheApproval
	if isOSDF {
		v.SetDefault(param.Registry_RequireCacheApproval.GetName(), true)
	} else {
		v.SetDefault(param.Registry_RequireCacheApproval.GetName(), false)
	}
	// Registry.RequireKeyChaining
	v.SetDefault(param.Registry_RequireKeyChaining.GetName(), true)
	// Registry.RequireOriginApproval
	if isOSDF {
		v.SetDefault(param.Registry_RequireOriginApproval.GetName(), true)
	} else {
		v.SetDefault(param.Registry_RequireOriginApproval.GetName(), false)
	}
	// Server.AdLifetime
	v.SetDefault(param.Server_AdLifetime.GetName(), "10m")
	// Server.AdminGroups
	v.SetDefault(param.Server_AdminGroups.GetName(), []string{})
	// Server.AdvertisementInterval
	v.SetDefault(param.Server_AdvertisementInterval.GetName(), "1m")
	// Server.DatabaseBackup.Frequency
	v.SetDefault(param.Server_DatabaseBackup_Frequency.GetName(), "24h")
	// Server.DatabaseBackup.Location
	if isRoot {
		v.SetDefault(param.Server_DatabaseBackup_Location.GetName(), "/var/lib/pelican/backups")
	} else {
		{
			val := "${ConfigBase}/backups"
			val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
			v.SetDefault(param.Server_DatabaseBackup_Location.GetName(), val)
		}
	}
	// Server.DatabaseBackup.MaxCount
	v.SetDefault(param.Server_DatabaseBackup_MaxCount.GetName(), 10)
	// Server.DbLocation
	if isRoot {
		v.SetDefault(param.Server_DbLocation.GetName(), "/var/lib/pelican/pelican.sqlite")
	} else {
		{
			val := "${ConfigBase}/pelican.sqlite"
			val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
			v.SetDefault(param.Server_DbLocation.GetName(), val)
		}
	}
	// Server.DirectorUrls
	v.SetDefault(param.Server_DirectorUrls.GetName(), []string{})
	// Server.DropPrivileges
	v.SetDefault(param.Server_DropPrivileges.GetName(), false)
	// Server.EnablePKCS11
	v.SetDefault(param.Server_EnablePKCS11.GetName(), false)
	// Server.EnablePprof
	v.SetDefault(param.Server_EnablePprof.GetName(), false)
	// Server.EnableUI
	v.SetDefault(param.Server_EnableUI.GetName(), true)
	// Server.HealthMonitoringPublic
	v.SetDefault(param.Server_HealthMonitoringPublic.GetName(), false)
	// Server.Modules
	v.SetDefault(param.Server_Modules.GetName(), []string{})
	// Server.RegistrationRetryInterval
	v.SetDefault(param.Server_RegistrationRetryInterval.GetName(), "10s")
	// Server.SessionSecretFile
	{
		val := "${ConfigBase}/session-secret"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Server_SessionSecretFile.GetName(), val)
	}
	// Server.StartupTimeout
	v.SetDefault(param.Server_StartupTimeout.GetName(), "10s")
	// Server.TLSCACertificateFile
	{
		val := "${ConfigBase}/certificates/tlsca.pem"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Server_TLSCACertificateFile.GetName(), val)
	}
	// Server.TLSCAKey
	{
		val := "${ConfigBase}/certificates/tlsca.key"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Server_TLSCAKey.GetName(), val)
	}
	// Server.TLSCertificateChain
	{
		val := "${ConfigBase}/certificates/tls.crt"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Server_TLSCertificateChain.GetName(), val)
	}
	// Server.TLSKey
	{
		val := "${ConfigBase}/certificates/tls.key"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Server_TLSKey.GetName(), val)
	}
	// Server.UIActivationCodeFile
	{
		val := "${ConfigBase}/server-web-activation-code"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Server_UIActivationCodeFile.GetName(), val)
	}
	// Server.UIAdminUsers
	v.SetDefault(param.Server_UIAdminUsers.GetName(), []string{})
	// Server.UILoginRateLimit
	v.SetDefault(param.Server_UILoginRateLimit.GetName(), 1)
	// Server.UIPasswordFile
	{
		val := "${ConfigBase}/server-web-passwd"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Server_UIPasswordFile.GetName(), val)
	}
	// Server.UnprivilegedUser
	v.SetDefault(param.Server_UnprivilegedUser.GetName(), "pelican")
	// Server.WebConfigFile
	{
		val := "${ConfigBase}/web-config.yaml"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Server_WebConfigFile.GetName(), val)
	}
	// Server.WebHost
	v.SetDefault(param.Server_WebHost.GetName(), "0.0.0.0")
	// Server.WebPort
	v.SetDefault(param.Server_WebPort.GetName(), 8444)
	// Server.ExternalWebUrl
	{
		val := "https://${Server.Hostname}:${Server.WebPort}"
		val = strings.ReplaceAll(val, "${Server.Hostname}", v.GetString(param.Server_Hostname.GetName()))
		val = strings.ReplaceAll(val, "${Server.WebPort}", v.GetString(param.Server_WebPort.GetName()))
		v.SetDefault(param.Server_ExternalWebUrl.GetName(), val)
	}
	// Director.AdvertiseUrl
	{
		val := "${Server.ExternalWebUrl}"
		val = strings.ReplaceAll(val, "${Server.ExternalWebUrl}", v.GetString(param.Server_ExternalWebUrl.GetName()))
		v.SetDefault(param.Director_AdvertiseUrl.GetName(), val)
	}
	// Issuer.IssuerClaimValue
	{
		val := "${Server.ExternalWebUrl}"
		val = strings.ReplaceAll(val, "${Server.ExternalWebUrl}", v.GetString(param.Server_ExternalWebUrl.GetName()))
		v.SetDefault(param.Issuer_IssuerClaimValue.GetName(), val)
	}
	// Server.WebReadOnly
	v.SetDefault(param.Server_WebReadOnly.GetName(), false)
	// Shoveler.AMQPExchange
	v.SetDefault(param.Shoveler_AMQPExchange.GetName(), "shoveled-xrd")
	// Shoveler.AMQPTokenLocation
	{
		val := "${ConfigBase}/shoveler-token"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Shoveler_AMQPTokenLocation.GetName(), val)
	}
	// Shoveler.Enable
	v.SetDefault(param.Shoveler_Enable.GetName(), false)
	// Shoveler.MessageQueueProtocol
	v.SetDefault(param.Shoveler_MessageQueueProtocol.GetName(), "amqp")
	// Shoveler.OutputDestinations
	v.SetDefault(param.Shoveler_OutputDestinations.GetName(), []string{})
	// Shoveler.PortHigher
	v.SetDefault(param.Shoveler_PortHigher.GetName(), 9999)
	// Shoveler.PortLower
	v.SetDefault(param.Shoveler_PortLower.GetName(), 9930)
	// Shoveler.QueueDirectory
	if isRoot {
		v.SetDefault(param.Shoveler_QueueDirectory.GetName(), "/var/spool/pelican/shoveler/queue")
	} else {
		{
			val := "${ConfigBase}/shoveler/queue"
			val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
			v.SetDefault(param.Shoveler_QueueDirectory.GetName(), val)
		}
	}
	// Shoveler.VerifyHeader
	v.SetDefault(param.Shoveler_VerifyHeader.GetName(), false)
	// StagePlugin.Hook
	v.SetDefault(param.StagePlugin_Hook.GetName(), false)
	// TLSSkipVerify
	v.SetDefault(param.TLSSkipVerify.GetName(), false)
	// Topology.DisableCacheX509
	v.SetDefault(param.Topology_DisableCacheX509.GetName(), false)
	// Topology.DisableCaches
	v.SetDefault(param.Topology_DisableCaches.GetName(), false)
	// Topology.DisableDowntime
	v.SetDefault(param.Topology_DisableDowntime.GetName(), false)
	// Topology.DisableOriginX509
	v.SetDefault(param.Topology_DisableOriginX509.GetName(), false)
	// Topology.DisableOrigins
	v.SetDefault(param.Topology_DisableOrigins.GetName(), false)
	// Transport.BrokerEndpointCacheTTL
	v.SetDefault(param.Transport_BrokerEndpointCacheTTL.GetName(), "2m")
	// Transport.DialerKeepAlive
	v.SetDefault(param.Transport_DialerKeepAlive.GetName(), "30s")
	// Transport.DialerTimeout
	v.SetDefault(param.Transport_DialerTimeout.GetName(), "10s")
	// Transport.ExpectContinueTimeout
	v.SetDefault(param.Transport_ExpectContinueTimeout.GetName(), "1s")
	// Transport.IdleConnTimeout
	v.SetDefault(param.Transport_IdleConnTimeout.GetName(), "90s")
	// Transport.MaxIdleConns
	v.SetDefault(param.Transport_MaxIdleConns.GetName(), 30)
	// Transport.ResponseHeaderTimeout
	v.SetDefault(param.Transport_ResponseHeaderTimeout.GetName(), "10s")
	// Transport.TLSHandshakeTimeout
	v.SetDefault(param.Transport_TLSHandshakeTimeout.GetName(), "15s")
	// Xrootd.AuthRefreshInterval
	v.SetDefault(param.Xrootd_AuthRefreshInterval.GetName(), "5m")
	// Xrootd.Authfile
	{
		val := "${ConfigBase}/xrootd/authfile"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Xrootd_Authfile.GetName(), val)
	}
	// Xrootd.AutoShutdownEnabled
	v.SetDefault(param.Xrootd_AutoShutdownEnabled.GetName(), true)
	// Xrootd.ConfigUpdateFailureTimeout
	v.SetDefault(param.Xrootd_ConfigUpdateFailureTimeout.GetName(), "1h")
	// Xrootd.DetailedMonitoringHost
	if isOSDF {
		v.SetDefault(param.Xrootd_DetailedMonitoringHost.GetName(), "xrd-mon.osgstorage.org")
	}
	// Xrootd.DetailedMonitoringPort
	v.SetDefault(param.Xrootd_DetailedMonitoringPort.GetName(), 9930)
	// Xrootd.EnableLocalMonitoring
	v.SetDefault(param.Xrootd_EnableLocalMonitoring.GetName(), true)
	// Xrootd.HttpMaxDelay
	v.SetDefault(param.Xrootd_HttpMaxDelay.GetName(), "9s")
	// Xrootd.MacaroonsKeyFile
	{
		val := "${ConfigBase}/macaroons-secret"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Xrootd_MacaroonsKeyFile.GetName(), val)
	}
	// Xrootd.ManagerHost
	if isOSDF {
		v.SetDefault(param.Xrootd_ManagerHost.GetName(), "redirector.osgstorage.org")
	}
	// Xrootd.ManagerPort
	v.SetDefault(param.Xrootd_ManagerPort.GetName(), 1213)
	// Xrootd.MaxStartupWait
	v.SetDefault(param.Xrootd_MaxStartupWait.GetName(), "10s")
	// Xrootd.MaxThreads
	v.SetDefault(param.Xrootd_MaxThreads.GetName(), 20000)
	// Xrootd.RobotsTxtFile
	{
		val := "${ConfigBase}/robots.txt"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Xrootd_RobotsTxtFile.GetName(), val)
	}
	// Xrootd.ScitokensConfig
	{
		val := "${ConfigBase}/xrootd/scitokens.cfg"
		val = strings.ReplaceAll(val, "${ConfigBase}", v.GetString(param.ConfigBase.GetName()))
		v.SetDefault(param.Xrootd_ScitokensConfig.GetName(), val)
	}
	// Xrootd.ShutdownTimeout
	v.SetDefault(param.Xrootd_ShutdownTimeout.GetName(), "1m")
	// Xrootd.Sitename
	{
		val := "${Server.Hostname}"
		val = strings.ReplaceAll(val, "${Server.Hostname}", v.GetString(param.Server_Hostname.GetName()))
		v.SetDefault(param.Xrootd_Sitename.GetName(), val)
	}
	// Xrootd.SummaryMonitoringHost
	if isOSDF {
		v.SetDefault(param.Xrootd_SummaryMonitoringHost.GetName(), "xrd-report.osgstorage.org")
	}
	// Xrootd.SummaryMonitoringPort
	v.SetDefault(param.Xrootd_SummaryMonitoringPort.GetName(), 9931)
}

// ApplyClientDefaults overrides base defaults with client-specific values.
// Call after SetParameterDefaults.
func ApplyClientDefaults(v *viper.Viper) {
	// Logging.Level
	v.SetDefault(param.Logging_Level.GetName(), "warn")
}

// ApplyServerDefaults overrides base defaults with server-specific values.
// Call after SetParameterDefaults.
func ApplyServerDefaults(v *viper.Viper) {
	// Logging.Level
	v.SetDefault(param.Logging_Level.GetName(), "info")
}
