// Code generated by go generate; DO NOT EDIT.

package config

import (
	"github.com/spf13/viper"
)

type StringParam struct {
	name string
}

type BoolParam struct {
	name string
}

type IntParam struct {
	name string
}

func (sP StringParam) GetString() string {
	return viper.GetString(sP.name)
}

func (iP IntParam) GetInt() int {
	return viper.GetInt(iP.name)
}

func (bP BoolParam) GetBool() bool {
	return viper.GetBool(bP.name)
}

var (
	DirectorUrl = StringParam{"DirectorUrl"}
	Director_DefaultResponse = StringParam{"Director.DefaultResponse"}
	GeoIPLocation = StringParam{"GeoIPLocation"}
	IssuerKey = StringParam{"IssuerKey"}
	MaxMindKeyFile = StringParam{"MaxMindKeyFile"}
	NSRegistryLocation = StringParam{"NSRegistryLocation"}
	NamespaceUrl = StringParam{"NamespaceUrl"}
	OIDC_ClientIDFile = StringParam{"OIDC.ClientIDFile"}
	OIDC_ClientSecretFile = StringParam{"OIDC.ClientSecretFile"}
	OIDC_DeviceAuthEndpoint = StringParam{"OIDC.DeviceAuthEndpoint"}
	OIDC_TokenEndpoint = StringParam{"OIDC.TokenEndpoint"}
	OIDC_UserInfoEndpoint = StringParam{"OIDC.UserInfoEndpoint"}
	RobotsTxtFile = StringParam{"RobotsTxtFile"}
	ScitokensConfig = StringParam{"ScitokensConfig"}
	TLSCertificate = StringParam{"TLSCertificate"}
	TLSKey = StringParam{"TLSKey"}
	TopologyNamespaceURL = StringParam{"TopologyNamespaceURL"}
	XrootdRun = StringParam{"XrootdRun"}
)

var (
	WebPort = IntParam{"WebPort"}
)

var (
	TLSSkipVerify = BoolParam{"TLSSkipVerify"}
)
