// Code generated by go generate; DO NOT EDIT.
/***************************************************************
 *
 * Copyright (C) 2026, Pelican Project, Morgridge Institute for Research
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ***************************************************************/

package param

// derivedOrder lists every parameter whose YAML default contains a
// ${Param.Name} placeholder, in topological dependency order. The hand-
// written ResolveDerivedDefaults function walks this slice and re-substitutes
// each entry's currently-registered template against viper. Generated by
// 'cd generate && go run .' from docs/parameters.yaml.
func init() {
	derivedOrder = []string{
		"Cache.DbLocation",
		"Cache.FedTokenLocation",
		"Cache.ClientStatisticsLocation",
		"Cache.DataLocations",
		"Cache.MetaLocations",
		"Cache.NamespaceLocation",
		"Cache.Url",
		"Director.DbLocation",
		"Director.GeoIPLocation",
		"IssuerKey",
		"IssuerKeysDirectory",
		"LocalCache.DataLocation",
		"LocalCache.Socket",
		"Lotman.DbLocation",
		"Lotman.LotHome",
		"Monitoring.DataLocation",
		"OIDC.ClientIDFile",
		"OIDC.ClientSecretFile",
		"Origin.DbLocation",
		"Origin.FedTokenLocation",
		"Origin.UploadTempLocation",
		"Origin.Url",
		"Origin.TokenAudience",
		"Registry.DbLocation",
		"Server.DatabaseBackup.Location",
		"Server.DbLocation",
		"Server.SessionSecretFile",
		"Server.TLSCACertificateFile",
		"Server.TLSCAKey",
		"Server.TLSCertificate",
		"Server.TLSCertificateChain",
		"Server.TLSKey",
		"Server.UIActivationCodeFile",
		"Server.UIPasswordFile",
		"Server.WebConfigFile",
		"Server.ExternalWebUrl",
		"Director.AdvertiseUrl",
		"Issuer.IssuerClaimValue",
		"Shoveler.AMQPTokenLocation",
		"Shoveler.QueueDirectory",
		"Xrootd.Authfile",
		"Xrootd.MacaroonsKeyFile",
		"Xrootd.RobotsTxtFile",
		"Xrootd.ScitokensConfig",
		"Xrootd.Sitename",
	}
}
