
// Code generated by go generate; DO NOT EDIT.
package param

import (
	"time"
)

type config struct {
	Cache struct {
		DataLocation string
		EnableVoms bool
		ExportLocation string
		Port int
		XRootDPrefix string
	}
	Client struct {
		DisableHttpProxy bool
		DisableProxyFallback bool
		MinimumDownloadSpeed int
		SlowTransferRampupTime int
		SlowTransferWindow int
		StoppedTransferTimeout int
	}
	ConfigDir string
	Debug bool
	Director struct {
		CacheResponseHostnames []string
		DefaultResponse string
		GeoIPLocation string
		MaxMindKeyFile string
		OriginResponseHostnames []string
	}
	DisableHttpProxy bool
	DisableProxyFallback bool
	Federation struct {
		DirectorUrl string
		DiscoveryUrl string
		JwkUrl string
		NamespaceUrl string
		RegistryUrl string
		TopologyNamespaceUrl string
		TopologyReloadInterval time.Duration
	}
	GeoIPOverrides interface{}
	Issuer struct {
		AuthenticationSource string
		AuthorizationTemplates interface{}
		GroupFile string
		GroupRequirements []string
		GroupSource string
		OIDCAuthenticationRequirements interface{}
		OIDCAuthenticationUserClaim string
		QDLLocation string
		ScitokensServerLocation string
		TomcatLocation string
	}
	IssuerKey string
	Logging struct {
		Level string
		LogLocation string
	}
	MinimumDownloadSpeed int
	Monitoring struct {
		AggregatePrefixes []string
		DataLocation string
		MetricAuthorization bool
		PortHigher int
		PortLower int
		TokenExpiresIn time.Duration
		TokenRefreshInterval time.Duration
	}
	OIDC struct {
		AuthorizationEndpoint string
		ClientID string
		ClientIDFile string
		ClientRedirectHostname string
		ClientSecretFile string
		DeviceAuthEndpoint string
		Issuer string
		TokenEndpoint string
		UserInfoEndpoint string
	}
	Origin struct {
		EnableCmsd bool
		EnableDirListing bool
		EnableIssuer bool
		EnableUI bool
		EnableVoms bool
		ExportVolume string
		Mode string
		Multiuser bool
		NamespacePrefix string
		S3AccessKeyfile string
		S3Bucket string
		S3Region string
		S3SecretKeyfile string
		S3ServiceName string
		S3ServiceUrl string
		ScitokensDefaultUser string
		ScitokensMapSubject bool
		ScitokensNameMapFile string
		ScitokensRestrictedPaths []string
		ScitokensUsernameClaim string
		SelfTest bool
		Url string
		XRootDPrefix string
	}
	Plugin struct {
		Token string
	}
	Registry struct {
		DbLocation string
		RequireKeyChaining bool
	}
	Server struct {
		EnableUI bool
		ExternalWebUrl string
		Hostname string
		IssuerHostname string
		IssuerJwks string
		IssuerPort int
		IssuerUrl string
		Modules []string
		SessionSecretFile string
		TLSCACertificateDirectory string
		TLSCACertificateFile string
		TLSCAKey string
		TLSCertificate string
		TLSKey string
		UIActivationCodeFile string
		UIPasswordFile string
		WebHost string
		WebPort int
	}
	StagePlugin struct {
		Hook bool
		MountPrefix string
		OriginPrefix string
		ShadowOriginPrefix string
	}
	TLSSkipVerify bool
	Transport struct {
		DialerKeepAlive time.Duration
		DialerTimeout time.Duration
		ExpectContinueTimeout time.Duration
		IdleConnTimeout time.Duration
		MaxIdleConns int
		ResponseHeaderTimeout time.Duration
		TLSHandshakeTimeout time.Duration
	}
	Xrootd struct {
		Authfile string
		DetailedMonitoringHost string
		LocalMonitoringHost string
		MacaroonsKeyFile string
		ManagerHost string
		Mount string
		Port int
		RobotsTxtFile string
		RunLocation string
		ScitokensConfig string
		Sitename string
		SummaryMonitoringHost string
	}
}
