// Code generated by go generate; DO NOT EDIT.

package param

import (
	"time"
)

type config struct {
	Cache struct {
		DataLocation string
		EnableVoms bool
		ExportLocation string
		Port int
		XRootDPrefix string
	}
	Client struct {
		DisableHttpProxy bool
		DisableProxyFallback bool
		MinimumDownloadSpeed int
		SlowTransferRampupTime int
		SlowTransferWindow int
		StoppedTransferTimeout int
	}
	ConfigDir string
	Debug bool
	Director struct {
		AdvertisementTTL time.Duration
		CacheResponseHostnames []string
		DefaultResponse string
		GeoIPLocation string
		MaxMindKeyFile string
		OriginCacheHealthTestInterval time.Duration
		OriginResponseHostnames []string
	}
	DisableHttpProxy bool
	DisableProxyFallback bool
	Federation struct {
		DirectorUrl string
		DiscoveryUrl string
		JwkUrl string
		NamespaceUrl string
		RegistryUrl string
		TopologyNamespaceUrl string
		TopologyReloadInterval time.Duration
	}
	GeoIPOverrides interface{}
	Issuer struct {
		AuthenticationSource string
		AuthorizationTemplates interface{}
		GroupFile string
		GroupRequirements []string
		GroupSource string
		OIDCAuthenticationRequirements interface{}
		OIDCAuthenticationUserClaim string
		QDLLocation string
		ScitokensServerLocation string
		TomcatLocation string
	}
	IssuerKey string
	Logging struct {
		DisableProgressBars bool
		Level string
		LogLocation string
	}
	MinimumDownloadSpeed int
	Monitoring struct {
		AggregatePrefixes []string
		DataLocation string
		MetricAuthorization bool
		PortHigher int
		PortLower int
		TokenExpiresIn time.Duration
		TokenRefreshInterval time.Duration
	}
	OIDC struct {
		AuthorizationEndpoint string
		ClientID string
		ClientIDFile string
		ClientRedirectHostname string
		ClientSecretFile string
		DeviceAuthEndpoint string
		Issuer string
		TokenEndpoint string
		UserInfoEndpoint string
	}
	Origin struct {
		EnableCmsd bool
		EnableDirListing bool
		EnableFallbackRead bool
		EnableIssuer bool
		EnableUI bool
		EnableVoms bool
		EnableWrite bool
		ExportVolume string
		Mode string
		Multiuser bool
		NamespacePrefix string
		S3AccessKeyfile string
		S3Bucket string
		S3Region string
		S3SecretKeyfile string
		S3ServiceName string
		S3ServiceUrl string
		ScitokensDefaultUser string
		ScitokensMapSubject bool
		ScitokensNameMapFile string
		ScitokensRestrictedPaths []string
		ScitokensUsernameClaim string
		SelfTest bool
		Url string
		XRootDPrefix string
	}
	Plugin struct {
		Token string
	}
	Registry struct {
		AdminUsers []string
		DbLocation string
		Institutions interface{}
		InstitutionsUrl string
		InstitutionsUrlReloadMinutes time.Duration
		RequireKeyChaining bool
	}
	Server struct {
		EnableUI bool
		ExternalWebUrl string
		Hostname string
		IssuerHostname string
		IssuerJwks string
		IssuerPort int
		IssuerUrl string
		Modules []string
		RegistrationRetryInterval time.Duration
		SessionSecretFile string
		TLSCACertificateDirectory string
		TLSCACertificateFile string
		TLSCAKey string
		TLSCertificate string
		TLSKey string
		UIActivationCodeFile string
		UIPasswordFile string
		WebHost string
		WebPort int
	}
	Shoveler struct {
		Cert string
		CertKey string
		Enable bool
		Exchange string
		IPMapping interface{}
		MessageQueueProtocol string
		OutputDestinations []string
		Password string
		PortHigher int
		PortLower int
		QueueDirectory string
		TokenLocation string
		Topic string
		URL string
		Username string
		VerifyHeader bool
	}
	StagePlugin struct {
		Hook bool
		MountPrefix string
		OriginPrefix string
		ShadowOriginPrefix string
	}
	TLSSkipVerify bool
	Transport struct {
		DialerKeepAlive time.Duration
		DialerTimeout time.Duration
		ExpectContinueTimeout time.Duration
		IdleConnTimeout time.Duration
		MaxIdleConns int
		ResponseHeaderTimeout time.Duration
		TLSHandshakeTimeout time.Duration
	}
	Xrootd struct {
		Authfile string
		DetailedMonitoringHost string
		LocalMonitoringHost string
		MacaroonsKeyFile string
		ManagerHost string
		Mount string
		Port int
		RobotsTxtFile string
		RunLocation string
		ScitokensConfig string
		Sitename string
		SummaryMonitoringHost string
	}
}


type configWithType struct {
	Cache struct {
		DataLocation struct { Type string; Value string }
		EnableVoms struct { Type string; Value bool }
		ExportLocation struct { Type string; Value string }
		Port struct { Type string; Value int }
		XRootDPrefix struct { Type string; Value string }
	}
	Client struct {
		DisableHttpProxy struct { Type string; Value bool }
		DisableProxyFallback struct { Type string; Value bool }
		MinimumDownloadSpeed struct { Type string; Value int }
		SlowTransferRampupTime struct { Type string; Value int }
		SlowTransferWindow struct { Type string; Value int }
		StoppedTransferTimeout struct { Type string; Value int }
	}
	ConfigDir struct { Type string; Value string }
	Debug struct { Type string; Value bool }
	Director struct {
		AdvertisementTTL struct { Type string; Value time.Duration }
		CacheResponseHostnames struct { Type string; Value []string }
		DefaultResponse struct { Type string; Value string }
		GeoIPLocation struct { Type string; Value string }
		MaxMindKeyFile struct { Type string; Value string }
		OriginCacheHealthTestInterval struct { Type string; Value time.Duration }
		OriginResponseHostnames struct { Type string; Value []string }
	}
	DisableHttpProxy struct { Type string; Value bool }
	DisableProxyFallback struct { Type string; Value bool }
	Federation struct {
		DirectorUrl struct { Type string; Value string }
		DiscoveryUrl struct { Type string; Value string }
		JwkUrl struct { Type string; Value string }
		NamespaceUrl struct { Type string; Value string }
		RegistryUrl struct { Type string; Value string }
		TopologyNamespaceUrl struct { Type string; Value string }
		TopologyReloadInterval struct { Type string; Value time.Duration }
	}
	GeoIPOverrides struct { Type string; Value interface{} }
	Issuer struct {
		AuthenticationSource struct { Type string; Value string }
		AuthorizationTemplates struct { Type string; Value interface{} }
		GroupFile struct { Type string; Value string }
		GroupRequirements struct { Type string; Value []string }
		GroupSource struct { Type string; Value string }
		OIDCAuthenticationRequirements struct { Type string; Value interface{} }
		OIDCAuthenticationUserClaim struct { Type string; Value string }
		QDLLocation struct { Type string; Value string }
		ScitokensServerLocation struct { Type string; Value string }
		TomcatLocation struct { Type string; Value string }
	}
	IssuerKey struct { Type string; Value string }
	Logging struct {
		DisableProgressBars struct { Type string; Value bool }
		Level struct { Type string; Value string }
		LogLocation struct { Type string; Value string }
	}
	MinimumDownloadSpeed struct { Type string; Value int }
	Monitoring struct {
		AggregatePrefixes struct { Type string; Value []string }
		DataLocation struct { Type string; Value string }
		MetricAuthorization struct { Type string; Value bool }
		PortHigher struct { Type string; Value int }
		PortLower struct { Type string; Value int }
		TokenExpiresIn struct { Type string; Value time.Duration }
		TokenRefreshInterval struct { Type string; Value time.Duration }
	}
	OIDC struct {
		AuthorizationEndpoint struct { Type string; Value string }
		ClientID struct { Type string; Value string }
		ClientIDFile struct { Type string; Value string }
		ClientRedirectHostname struct { Type string; Value string }
		ClientSecretFile struct { Type string; Value string }
		DeviceAuthEndpoint struct { Type string; Value string }
		Issuer struct { Type string; Value string }
		TokenEndpoint struct { Type string; Value string }
		UserInfoEndpoint struct { Type string; Value string }
	}
	Origin struct {
		EnableCmsd struct { Type string; Value bool }
		EnableDirListing struct { Type string; Value bool }
		EnableFallbackRead struct { Type string; Value bool }
		EnableIssuer struct { Type string; Value bool }
		EnableUI struct { Type string; Value bool }
		EnableVoms struct { Type string; Value bool }
		EnableWrite struct { Type string; Value bool }
		ExportVolume struct { Type string; Value string }
		Mode struct { Type string; Value string }
		Multiuser struct { Type string; Value bool }
		NamespacePrefix struct { Type string; Value string }
		S3AccessKeyfile struct { Type string; Value string }
		S3Bucket struct { Type string; Value string }
		S3Region struct { Type string; Value string }
		S3SecretKeyfile struct { Type string; Value string }
		S3ServiceName struct { Type string; Value string }
		S3ServiceUrl struct { Type string; Value string }
		ScitokensDefaultUser struct { Type string; Value string }
		ScitokensMapSubject struct { Type string; Value bool }
		ScitokensNameMapFile struct { Type string; Value string }
		ScitokensRestrictedPaths struct { Type string; Value []string }
		ScitokensUsernameClaim struct { Type string; Value string }
		SelfTest struct { Type string; Value bool }
		Url struct { Type string; Value string }
		XRootDPrefix struct { Type string; Value string }
	}
	Plugin struct {
		Token struct { Type string; Value string }
	}
	Registry struct {
		AdminUsers struct { Type string; Value []string }
		DbLocation struct { Type string; Value string }
		Institutions struct { Type string; Value interface{} }
		InstitutionsUrl struct { Type string; Value string }
		InstitutionsUrlReloadMinutes struct { Type string; Value time.Duration }
		RequireKeyChaining struct { Type string; Value bool }
	}
	Server struct {
		EnableUI struct { Type string; Value bool }
		ExternalWebUrl struct { Type string; Value string }
		Hostname struct { Type string; Value string }
		IssuerHostname struct { Type string; Value string }
		IssuerJwks struct { Type string; Value string }
		IssuerPort struct { Type string; Value int }
		IssuerUrl struct { Type string; Value string }
		Modules struct { Type string; Value []string }
		RegistrationRetryInterval struct { Type string; Value time.Duration }
		SessionSecretFile struct { Type string; Value string }
		TLSCACertificateDirectory struct { Type string; Value string }
		TLSCACertificateFile struct { Type string; Value string }
		TLSCAKey struct { Type string; Value string }
		TLSCertificate struct { Type string; Value string }
		TLSKey struct { Type string; Value string }
		UIActivationCodeFile struct { Type string; Value string }
		UIPasswordFile struct { Type string; Value string }
		WebHost struct { Type string; Value string }
		WebPort struct { Type string; Value int }
	}
	Shoveler struct {
		Cert struct { Type string; Value string }
		CertKey struct { Type string; Value string }
		Enable struct { Type string; Value bool }
		Exchange struct { Type string; Value string }
		IPMapping struct { Type string; Value interface{} }
		MessageQueueProtocol struct { Type string; Value string }
		OutputDestinations struct { Type string; Value []string }
		Password struct { Type string; Value string }
		PortHigher struct { Type string; Value int }
		PortLower struct { Type string; Value int }
		QueueDirectory struct { Type string; Value string }
		TokenLocation struct { Type string; Value string }
		Topic struct { Type string; Value string }
		URL struct { Type string; Value string }
		Username struct { Type string; Value string }
		VerifyHeader struct { Type string; Value bool }
	}
	StagePlugin struct {
		Hook struct { Type string; Value bool }
		MountPrefix struct { Type string; Value string }
		OriginPrefix struct { Type string; Value string }
		ShadowOriginPrefix struct { Type string; Value string }
	}
	TLSSkipVerify struct { Type string; Value bool }
	Transport struct {
		DialerKeepAlive struct { Type string; Value time.Duration }
		DialerTimeout struct { Type string; Value time.Duration }
		ExpectContinueTimeout struct { Type string; Value time.Duration }
		IdleConnTimeout struct { Type string; Value time.Duration }
		MaxIdleConns struct { Type string; Value int }
		ResponseHeaderTimeout struct { Type string; Value time.Duration }
		TLSHandshakeTimeout struct { Type string; Value time.Duration }
	}
	Xrootd struct {
		Authfile struct { Type string; Value string }
		DetailedMonitoringHost struct { Type string; Value string }
		LocalMonitoringHost struct { Type string; Value string }
		MacaroonsKeyFile struct { Type string; Value string }
		ManagerHost struct { Type string; Value string }
		Mount struct { Type string; Value string }
		Port struct { Type string; Value int }
		RobotsTxtFile struct { Type string; Value string }
		RunLocation struct { Type string; Value string }
		ScitokensConfig struct { Type string; Value string }
		Sitename struct { Type string; Value string }
		SummaryMonitoringHost struct { Type string; Value string }
	}
}
