---
name: Check Go Generate Has Been Run

on:
  push:
    branches:
      - "main"
      - "v[0-9]+.[0-9]+.*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-go-generate:
    name: Check Go Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set Go version
        # Determine the string to use in setup-go's "go-version" input.
        id: go-version
        run: |
          version=$(grep -E '^go[[:space:]]*[0-9]+\.[0-9]+' go.mod | grep -oE '[0-9]+\.[0-9]+')
          echo "version=${version}.x" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
        with:
          go-version: "${{ steps.go-version.outputs.version }}"
          check-latest: true
          cache: false

      - name: Run Go Generate
        run: go generate ./...

      - name: Validate that generated files are up to date
        run: |
          if git diff --quiet; then
            echo "No changes found."
          else
            echo "Changes detected. Here are the details:"
            git diff
            exit 1
          fi
