# .github/workflows/release.yaml
name: Generate Release Artifacts

on:
  push:
    tags:
      # only run release on v7.0.0 and up
      # Match against v7.0.0, v7.0.0-rc.1, v7.0.0-rc.2, etc.
      - v[7-9]\.[0-9]+\.[0-9]+
      - v[7-9]\.[0-9]+\.[0-9]+-rc\.[0-9]+
      - v[1-9][0-9]+\.[0-9]+\.[0-9]+
      - v[1-9][0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set Go version
        # Determine the string to use in setup-go's "go-version" input.
        id: go-version
        run: |
          version=$(grep -E '^go[[:space:]]*[0-9]+\.[0-9]+' go.mod | grep -oE '[0-9]+\.[0-9]+')
          echo "version=${version}.x" >> $GITHUB_OUTPUT
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "${{ steps.go-version.outputs.version }}"
          check-latest: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

  # After the release is created, the post-release workflow will toggle the webhook to update pelicanplatform.org
  upload-release:
    needs: goreleaser
    uses: ./.github/workflows/post-release.yaml
