name: Run Tests (Linux) [on pull request]

on:
  pull_request:
  repository_dispatch:
    types:
      - dispatch-build
  workflow_dispatch:

# On a pull request, we cannot build and push a newer image in which to run
# the tests. Thus, we use the most recent container image that was built.

jobs:
  test-linux-pull-request:
    uses: ./.github/workflows/test-linux.yml
    with:
      image: hub.opensciencegrid.org/pelican_platform/pelican-test:latest-itb
