/***************************************************************
 *
 * Copyright (C) 2026, Pelican Project, Morgridge Institute for Research
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ***************************************************************/

package metrics

import (
	"encoding/binary"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/pelicanplatform/pelican/param"
)

// resetTestCaches clears all monitoring caches used by tests and registers
// a cleanup to clear them again when the test finishes.
func resetTestCaches(t *testing.T) {
	t.Helper()
	sessions.DeleteAll()
	userids.DeleteAll()
	transfers.DeleteAll()
	t.Cleanup(func() {
		sessions.DeleteAll()
		userids.DeleteAll()
		transfers.DeleteAll()
	})
}

// enableShoveler sets Shoveler.Enable=true for the duration of the test
// so that BeginTransferMonitor / EmitTransferEvent actually produce packets.
func enableShoveler(t *testing.T) {
	t.Helper()
	require.NoError(t, param.Reset())
	require.NoError(t, param.Set(param.Shoveler_Enable.GetName(), true))
	t.Cleanup(func() { require.NoError(t, param.Reset()) })
}

// TestBuildUserLoginPacketRoundTrip verifies that a user login ('u') packet
// generated by the internal backend can be parsed by handlePacket and that
// user/auth fields are correctly recovered.
func TestBuildUserLoginPacketRoundTrip(t *testing.T) {
	t.Run("authenticated-user-with-issuer", func(t *testing.T) {
		resetTestCaches(t)

		xrdUserId := XrdUserId{
			Prot: "https",
			User: "testuser",
			Pid:  1,
			Sid:  12345,
			Host: "192.168.1.100",
		}

		event := TransferEvent{
			AuthProtocol: "https",
			UserDN:       "testuser",
			Role:         "TestRole",
			Issuer:       "https://issuer.example.com",
		}

		packet, err := buildUserLoginPacket(1, 42, xrdUserId, event)
		require.NoError(t, err, "Failed to build user login packet")
		require.NotEmpty(t, packet)

		// Parse the packet through handlePacket
		err = handlePacket(packet)
		require.NoError(t, err, "handlePacket failed to parse user login packet")

		// Verify that the session was registered
		userId := UserId{Id: 42}
		sessionItem := sessions.Get(userId)
		require.NotNil(t, sessionItem, "Session not found for user ID 42")

		record := sessionItem.Value()
		assert.Equal(t, "https", record.AuthenticationProtocol, "Auth protocol mismatch")
		assert.Equal(t, "testuser", record.DN, "DN mismatch")
		assert.Equal(t, "https://issuer.example.com", record.Org, "Org should carry the issuer URL")
		assert.Equal(t, "TestRole", record.Role, "Role mismatch")

		// Verify XrdUserId was correctly registered
		assert.Equal(t, "https", record.XrdUserId.Prot, "XrdUserId.Prot mismatch")
		assert.Equal(t, "testuser", record.XrdUserId.User, "XrdUserId.User mismatch")
		assert.Equal(t, "192.168.1.100", record.XrdUserId.Host, "XrdUserId.Host mismatch")
	})

	t.Run("unauthenticated-public-access", func(t *testing.T) {
		resetTestCaches(t)

		xrdUserId := XrdUserId{
			Prot: "https",
			User: "anonymous",
			Pid:  1,
			Sid:  12345,
			Host: "10.0.0.1",
		}

		event := TransferEvent{
			AuthProtocol: "https",
			UserDN:       "",
			Role:         "",
		}

		packet, err := buildUserLoginPacket(2, 43, xrdUserId, event)
		require.NoError(t, err, "Failed to build user login packet for public access")

		err = handlePacket(packet)
		require.NoError(t, err, "handlePacket failed for public access packet")

		userId := UserId{Id: 43}
		sessionItem := sessions.Get(userId)
		require.NotNil(t, sessionItem, "Session not found for anonymous user")

		record := sessionItem.Value()
		assert.Equal(t, "https", record.AuthenticationProtocol)
		assert.Empty(t, record.DN, "DN should be empty for public access")
		assert.Empty(t, record.Org, "Org should be empty for public access")
		assert.Empty(t, record.Role, "Role should be empty for public access")
		assert.Equal(t, "anonymous", record.XrdUserId.User, "Anonymous user should have 'anonymous' user ID")
	})
}

// TestBuildFStreamOpenCloseRoundTrip verifies that f-stream open and close packets
// generated by the internal backend can be parsed by handlePacket and that file
// paths, user associations, and transfer bytes are correctly recovered.
func TestBuildFStreamOpenCloseRoundTrip(t *testing.T) {
	t.Run("read-transfer-with-authenticated-user", func(t *testing.T) {
		resetTestCaches(t)

		// First create a session so the file open can reference a user
		userId := uint32(50)
		xrdUserId := XrdUserId{
			Prot: "https",
			User: "readuser",
			Pid:  1,
			Sid:  12345,
			Host: "10.0.0.5",
		}
		event := TransferEvent{
			Path:         "/test/data/file.dat",
			ReadBytes:    1048576, // 1MB
			WriteBytes:   0,
			ReadOps:      10,
			WriteOps:     0,
			ClientIP:     "10.0.0.5",
			UserDN:       "readuser",
			Role:         "reader",
			AuthProtocol: "https",
			Issuer:       "https://tokens.example.com",
			StartTime:    time.Now().Add(-5 * time.Second),
			EndTime:      time.Now(),
		}

		// Build and parse the user login packet first
		loginPacket, err := buildUserLoginPacket(1, userId, xrdUserId, event)
		require.NoError(t, err)
		err = handlePacket(loginPacket)
		require.NoError(t, err)

		// Build and parse the f-stream open packet
		fileId := uint32(100)
		openPacket, err := buildFStreamOpenPacket(2, fileId, userId, event)
		require.NoError(t, err, "Failed to build f-stream open packet")
		require.NotEmpty(t, openPacket)

		err = handlePacket(openPacket)
		require.NoError(t, err, "handlePacket failed to parse f-stream open packet")

		// Verify transfer entry was created
		transferItem := transfers.Get(FileId{Id: fileId})
		require.NotNil(t, transferItem, "Transfer should exist after open")

		// Build and parse the f-stream close packet
		closePacket, err := buildFStreamClosePacket(3, fileId, event.ReadBytes, event.WriteBytes, event.ReadOps, event.WriteOps)
		require.NoError(t, err, "Failed to build f-stream close packet")

		err = handlePacket(closePacket)
		require.NoError(t, err, "handlePacket failed to parse f-stream close packet")

		// After close, the transfer should be removed
		transferItem = transfers.Get(FileId{Id: fileId})
		assert.Nil(t, transferItem, "Transfer should be deleted after close")
	})

	t.Run("write-transfer", func(t *testing.T) {
		resetTestCaches(t)

		userId := uint32(51)
		xrdUserId := XrdUserId{
			Prot: "https",
			User: "writeuser",
			Pid:  1,
			Sid:  12346,
			Host: "10.0.0.6",
		}
		event := TransferEvent{
			Path:         "/test/uploads/data.bin",
			ReadBytes:    0,
			WriteBytes:   2097152, // 2MB
			ReadOps:      0,
			WriteOps:     5,
			ClientIP:     "10.0.0.6",
			UserDN:       "writeuser",
			Role:         "writer",
			AuthProtocol: "https",
			Issuer:       "https://auth.example.com",
			StartTime:    time.Now().Add(-3 * time.Second),
			EndTime:      time.Now(),
		}

		loginPacket, err := buildUserLoginPacket(3, userId, xrdUserId, event)
		require.NoError(t, err)
		err = handlePacket(loginPacket)
		require.NoError(t, err)

		fileId := uint32(101)
		openPacket, err := buildFStreamOpenPacket(4, fileId, userId, event)
		require.NoError(t, err)

		err = handlePacket(openPacket)
		require.NoError(t, err, "handlePacket failed to parse write f-stream open packet")

		closePacket, err := buildFStreamClosePacket(5, fileId, event.ReadBytes, event.WriteBytes, event.ReadOps, event.WriteOps)
		require.NoError(t, err)

		err = handlePacket(closePacket)
		require.NoError(t, err, "handlePacket failed to parse write f-stream close packet")

		// Close should have removed the transfer
		transferItem := transfers.Get(FileId{Id: fileId})
		assert.Nil(t, transferItem, "Transfer should be deleted after close")
	})

	t.Run("public-access-no-token", func(t *testing.T) {
		resetTestCaches(t)

		userId := uint32(52)
		xrdUserId := XrdUserId{
			Prot: "https",
			User: "anonymous",
			Pid:  1,
			Sid:  12347,
			Host: "192.168.1.50",
		}
		event := TransferEvent{
			Path:         "/public/open-data.csv",
			ReadBytes:    512000,
			WriteBytes:   0,
			ReadOps:      3,
			WriteOps:     0,
			ClientIP:     "192.168.1.50",
			UserDN:       "",
			Role:         "",
			AuthProtocol: "https",
			Issuer:       "",
			StartTime:    time.Now().Add(-1 * time.Second),
			EndTime:      time.Now(),
		}

		loginPacket, err := buildUserLoginPacket(5, userId, xrdUserId, event)
		require.NoError(t, err)
		err = handlePacket(loginPacket)
		require.NoError(t, err)

		// Verify the session shows empty auth fields (public access)
		sessionItem := sessions.Get(UserId{Id: userId})
		require.NotNil(t, sessionItem)
		record := sessionItem.Value()
		assert.Equal(t, "https", record.AuthenticationProtocol)
		assert.Empty(t, record.DN, "DN should be empty for public access")
		assert.Empty(t, record.Org, "Org should be empty for public access")
		assert.Empty(t, record.Role, "Role should be empty for public access")

		fileId := uint32(102)
		openPacket, err := buildFStreamOpenPacket(6, fileId, userId, event)
		require.NoError(t, err)

		err = handlePacket(openPacket)
		require.NoError(t, err, "handlePacket failed for public access f-stream open")

		closePacket, err := buildFStreamClosePacket(7, fileId, event.ReadBytes, event.WriteBytes, event.ReadOps, event.WriteOps)
		require.NoError(t, err)

		err = handlePacket(closePacket)
		require.NoError(t, err, "handlePacket failed for public access f-stream close")
	})
}

// TestEmitTransferEventChannel verifies that EmitTransferEvent sends packets
// to the internal monitoring channel.
func TestEmitTransferEventChannel(t *testing.T) {
	enableShoveler(t)
	resetTestCaches(t)

	ch := GetInternalMonitorChan()

	// Drain any existing messages
	for len(ch) > 0 {
		<-ch
	}

	event := TransferEvent{
		Path:         "/test/channel-test.dat",
		ReadBytes:    4096,
		WriteBytes:   0,
		ReadOps:      1,
		WriteOps:     0,
		ClientIP:     "10.1.2.3",
		UserDN:       "channeluser",
		Role:         "tester",
		AuthProtocol: "https",
		Issuer:       "https://issuer.test.com",
		StartTime:    time.Now().Add(-1 * time.Second),
		EndTime:      time.Now(),
	}

	EmitTransferEvent(event)

	// Should have received 4 packets: user login + f-stream open + f-stream close + f-stream disc
	require.Eventually(t, func() bool {
		return len(ch) >= 4
	}, 2*time.Second, 10*time.Millisecond, "Expected 4 packets on internal channel")

	packet1 := <-ch
	require.NotEmpty(t, packet1)

	packet2 := <-ch
	require.NotEmpty(t, packet2)

	packet3 := <-ch
	require.NotEmpty(t, packet3)

	packet4 := <-ch
	require.NotEmpty(t, packet4)

	// Verify packet types
	assert.Equal(t, byte('u'), packet1[0], "First packet should be user login ('u')")
	assert.Equal(t, byte('f'), packet2[0], "Second packet should be f-stream open ('f')")
	assert.Equal(t, byte('f'), packet3[0], "Third packet should be f-stream close ('f')")
	assert.Equal(t, byte('f'), packet4[0], "Fourth packet should be f-stream disconnect ('f')")

	// Verify all packets can be parsed by handlePacket

	err := handlePacket(packet1)
	assert.NoError(t, err, "handlePacket should parse the user login packet")

	err = handlePacket(packet2)
	assert.NoError(t, err, "handlePacket should parse the f-stream open packet")

	err = handlePacket(packet3)
	assert.NoError(t, err, "handlePacket should parse the f-stream close packet")

	err = handlePacket(packet4)
	assert.NoError(t, err, "handlePacket should parse the f-stream disconnect packet")

}

// TestFStreamOpenPacketFormat verifies the detailed structure of generated
// f-stream open packets against the XRootD monitoring format specification.
func TestFStreamOpenPacketFormat(t *testing.T) {
	resetTestCaches(t)

	event := TransferEvent{
		Path:         "/namespace/project/dataset.root",
		ReadBytes:    999999,
		WriteBytes:   0,
		ReadOps:      42,
		WriteOps:     0,
		ClientIP:     "10.20.30.40",
		UserDN:       "scientist",
		Role:         "analyst",
		AuthProtocol: "https",
		StartTime:    time.Now().Add(-10 * time.Second),
		EndTime:      time.Now(),
	}

	packet, err := buildFStreamOpenPacket(7, 200, 60, event)
	require.NoError(t, err)

	// Verify header
	assert.Equal(t, byte('f'), packet[0], "Code should be 'f'")
	assert.Equal(t, byte(7), packet[1], "Pseq should match")

	// Verify packet length matches actual length
	plen := int(binary.BigEndian.Uint16(packet[2:4]))
	assert.Equal(t, len(packet), plen, "Plen should match actual packet length")

	// Verify the first record in the f-stream is a TOD (isTime) record
	// TOD starts at offset 8 (after the MonHeader)
	todRecType := packet[8]
	assert.Equal(t, byte(isTime), todRecType, "First record should be isTime (TOD)")

	// TOD RecSize should be 24
	todRecSize := int(binary.BigEndian.Uint16(packet[10:12]))
	assert.Equal(t, 24, todRecSize, "TOD RecSize should be 24")

	// After TOD, the next record should be isOpen
	openOffset := 8 + todRecSize
	openRecType := packet[openOffset]
	assert.Equal(t, byte(isOpen), openRecType, "Second record should be isOpen")
}

// TestUserLoginPacketUserIdParsing verifies that the user ID string format
// is correctly generated and can be parsed back.
func TestUserLoginPacketUserIdParsing(t *testing.T) {
	tests := []struct {
		name        string
		xrdUserId   XrdUserId
		expectedStr string
	}{
		{
			name: "standard-user",
			xrdUserId: XrdUserId{
				Prot: "https",
				User: "jdoe",
				Pid:  42,
				Sid:  99999,
				Host: "192.168.1.1",
			},
			expectedStr: "https/jdoe.42:99999@192.168.1.1",
		},
		{
			name: "anonymous-user",
			xrdUserId: XrdUserId{
				Prot: "https",
				User: "anonymous",
				Pid:  1,
				Sid:  12345,
				Host: "10.0.0.1",
			},
			expectedStr: "https/anonymous.1:12345@10.0.0.1",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			result := getUserIdString(tc.xrdUserId)
			assert.Equal(t, tc.expectedStr, result)

			// Verify it can be parsed back
			parsed, err := ParseXrdUserId(result)
			require.NoError(t, err)
			assert.Equal(t, tc.xrdUserId.Prot, parsed.Prot)
			assert.Equal(t, tc.xrdUserId.User, parsed.User)
			assert.Equal(t, tc.xrdUserId.Pid, parsed.Pid)
			assert.Equal(t, tc.xrdUserId.Sid, parsed.Sid)
			assert.Equal(t, tc.xrdUserId.Host, parsed.Host)
		})
	}
}

// TestEmitTransferEventAuthVariants tests that EmitTransferEvent correctly
// encodes different authentication scenarios.
func TestEmitTransferEventAuthVariants(t *testing.T) {
	enableShoveler(t)
	t.Run("scitoken-auth-with-issuer", func(t *testing.T) {
		resetTestCaches(t)

		// Drain channel
		ch := GetInternalMonitorChan()
		for len(ch) > 0 {
			<-ch
		}

		event := TransferEvent{
			Path:         "/federation/dataset/file.h5",
			ReadBytes:    50000,
			ReadOps:      5,
			ClientIP:     "172.16.0.50",
			UserDN:       "researcher@university.edu",
			Role:         "scientist",
			AuthProtocol: "https",
			Issuer:       "https://cilogon.org",
			StartTime:    time.Now().Add(-2 * time.Second),
			EndTime:      time.Now(),
		}

		EmitTransferEvent(event)

		// Expect 4 packets: u + open + close + disc (Issuer carried in 'u' packet's &o= field)
		require.Eventually(t, func() bool {
			return len(ch) >= 4
		}, 2*time.Second, 10*time.Millisecond)

		loginPacket := <-ch
		err := handlePacket(loginPacket)
		require.NoError(t, err)

		// Find the session that was just created and verify issuer was applied via 'u' packet
		var foundSession *UserRecord
		for _, key := range sessions.Keys() {
			item := sessions.Get(key)
			if item != nil {
				val := item.Value()
				if val.DN == "researcher@university.edu" {
					foundSession = &val
					break
				}
			}
		}
		require.NotNil(t, foundSession, "Session with DN 'researcher@university.edu' not found")
		assert.Equal(t, "https", foundSession.AuthenticationProtocol)
		assert.Equal(t, "https://cilogon.org", foundSession.Org, "Org should be the issuer URL from 'u' packet")
		assert.Equal(t, "scientist", foundSession.Role)

		// Parse the f-stream open, close, and disc packets
		openPacket := <-ch
		err = handlePacket(openPacket)
		require.NoError(t, err)

		closePacket := <-ch
		err = handlePacket(closePacket)
		require.NoError(t, err)

		discPacket := <-ch
		err = handlePacket(discPacket)
		require.NoError(t, err)

	})

	t.Run("public-data-no-auth", func(t *testing.T) {
		resetTestCaches(t)

		ch := GetInternalMonitorChan()
		for len(ch) > 0 {
			<-ch
		}

		event := TransferEvent{
			Path:         "/public/open-data/measurements.csv",
			ReadBytes:    1024,
			ReadOps:      1,
			ClientIP:     "203.0.113.42",
			UserDN:       "",
			Role:         "",
			AuthProtocol: "https",
			Issuer:       "",
			StartTime:    time.Now().Add(-1 * time.Second),
			EndTime:      time.Now(),
		}

		EmitTransferEvent(event)

		// Expect 4 packets: u + open + close + disc (no Issuer, no UserAgent)
		require.Eventually(t, func() bool {
			return len(ch) >= 4
		}, 2*time.Second, 10*time.Millisecond)

		loginPacket := <-ch
		err := handlePacket(loginPacket)
		require.NoError(t, err)

		// Find the session - should have anonymous user with empty auth fields
		var foundSession *UserRecord
		for _, key := range sessions.Keys() {
			item := sessions.Get(key)
			if item != nil {
				val := item.Value()
				if val.XrdUserId.Host == "203.0.113.42" {
					foundSession = &val
					break
				}
			}
		}
		require.NotNil(t, foundSession, "Session for public access not found")
		assert.Equal(t, "https", foundSession.AuthenticationProtocol)
		assert.Empty(t, foundSession.DN, "DN should be empty for public access")
		assert.Empty(t, foundSession.Org, "Org should be empty for public access")
		assert.Empty(t, foundSession.Role, "Role should be empty for public access")

		// Drain f-stream open, close, and disc packets
		<-ch
		<-ch
		<-ch

	})
}

// TestTransferMonitorLifecycle verifies the full Begin → EmitXfr → Close lifecycle:
// packets are parseable by handlePacket, the transfers cache is updated by isXfr,
// and the transfer is removed on isClose.
func TestTransferMonitorLifecycle(t *testing.T) {
	enableShoveler(t)
	resetTestCaches(t)

	ch := GetInternalMonitorChan()
	for len(ch) > 0 {
		<-ch
	}

	event := TransferEvent{
		Path:         "/lifecycle/test/bigfile.dat",
		ClientIP:     "10.99.1.1",
		UserDN:       "lifecycle-user",
		Role:         "tester",
		AuthProtocol: "https",
		Issuer:       "https://issuer.lifecycle.test",
		StartTime:    time.Now(),
	}

	// Begin should emit 2 packets: user login + f-stream open
	mon := BeginTransferMonitor(event)
	require.NotNil(t, mon, "BeginTransferMonitor should return a non-nil monitor")

	require.Eventually(t, func() bool {
		return len(ch) >= 2
	}, 2*time.Second, 10*time.Millisecond, "Expected 2 packets from BeginTransferMonitor")

	loginPacket := <-ch
	openPacket := <-ch
	assert.Equal(t, byte('u'), loginPacket[0], "First packet should be 'u' (user login)")
	assert.Equal(t, byte('f'), openPacket[0], "Second packet should be 'f' (f-stream open)")

	// Parse login + open so the session and transfer entry exist
	err := handlePacket(loginPacket)
	require.NoError(t, err, "handlePacket should parse login packet")
	err = handlePacket(openPacket)
	require.NoError(t, err, "handlePacket should parse open packet")

	// Verify the transfer entry was created by isOpen
	fileId := FileId{Id: mon.fileId}
	transferItem := transfers.Get(fileId)
	require.NotNil(t, transferItem, "Transfer entry should exist after isOpen")
	// Path is computed via computePrefix which returns "/" when monitorPaths is empty
	assert.Equal(t, "/", transferItem.Value().Path, "Transfer path should be / (no monitorPaths configured)")

	// EmitXfr should emit 1 packet: f-stream xfr
	mon.EmitXfr(500000, 0)
	require.Eventually(t, func() bool {
		return len(ch) >= 1
	}, 2*time.Second, 10*time.Millisecond, "Expected 1 xfr packet")

	xfrPacket := <-ch
	assert.Equal(t, byte('f'), xfrPacket[0], "Xfr packet should be 'f' (f-stream)")

	err = handlePacket(xfrPacket)
	require.NoError(t, err, "handlePacket should parse xfr packet")

	// Verify the transfer entry was updated with cumulative bytes
	transferItem = transfers.Get(fileId)
	require.NotNil(t, transferItem, "Transfer entry should still exist after isXfr")
	assert.Equal(t, uint64(500000), transferItem.Value().ReadBytes, "ReadBytes should be updated by isXfr")

	// Emit a second xfr with more bytes
	mon.EmitXfr(1500000, 0)
	require.Eventually(t, func() bool {
		return len(ch) >= 1
	}, 2*time.Second, 10*time.Millisecond, "Expected 1 more xfr packet")

	xfrPacket2 := <-ch
	err = handlePacket(xfrPacket2)
	require.NoError(t, err, "handlePacket should parse second xfr packet")

	transferItem = transfers.Get(fileId)
	require.NotNil(t, transferItem, "Transfer entry should still exist after second isXfr")
	assert.Equal(t, uint64(1500000), transferItem.Value().ReadBytes, "ReadBytes should be cumulative")

	// Close should emit 2 packets: f-stream close + f-stream disc
	mon.Close(2000000, 0, 20, 0)
	require.Eventually(t, func() bool {
		return len(ch) >= 2
	}, 2*time.Second, 10*time.Millisecond, "Expected 2 close packets")

	closePacket := <-ch
	assert.Equal(t, byte('f'), closePacket[0], "Close packet should be 'f' (f-stream)")

	err = handlePacket(closePacket)
	require.NoError(t, err, "handlePacket should parse close packet")

	// Verify the transfer entry was removed by isClose
	transferItem = transfers.Get(fileId)
	assert.Nil(t, transferItem, "Transfer entry should be deleted after isClose")

	discPacket := <-ch
	assert.Equal(t, byte('f'), discPacket[0], "Disc packet should be 'f' (f-stream)")
	err = handlePacket(discPacket)
	require.NoError(t, err, "handlePacket should parse disconnect packet")

}

// TestBuildFStreamXfrPacketFormat verifies the binary structure of an isXfr packet.
func TestBuildFStreamXfrPacketFormat(t *testing.T) {
	packet, err := buildFStreamXfrPacket(10, 300, 123456, 789012)
	require.NoError(t, err)

	// Verify header
	assert.Equal(t, byte('f'), packet[0], "Code should be 'f'")
	assert.Equal(t, byte(10), packet[1], "Pseq should match")

	// Verify packet length matches actual length
	plen := int(binary.BigEndian.Uint16(packet[2:4]))
	assert.Equal(t, len(packet), plen, "Plen should match actual packet length")

	// Expected total: 8 (MonHeader) + 24 (TOD) + 32 (XFR) = 64
	assert.Equal(t, 64, len(packet), "Total packet length should be 64")

	// Verify the first record in the f-stream is a TOD (isTime) record
	todRecType := packet[8]
	assert.Equal(t, byte(isTime), todRecType, "First record should be isTime (TOD)")
	todRecSize := int(binary.BigEndian.Uint16(packet[10:12]))
	assert.Equal(t, 24, todRecSize, "TOD RecSize should be 24")

	// Verify TOD NRecs0 = 1 (one isXfr record); NRecs0 is big-endian int16 at offset 12
	todNRecs0 := int16(binary.BigEndian.Uint16(packet[12:14]))
	assert.Equal(t, int16(1), todNRecs0, "TOD NRecs0 should be 1 (one isXfr)")

	// After TOD, the next record should be isXfr
	xfrOffset := 8 + todRecSize
	xfrRecType := packet[xfrOffset]
	assert.Equal(t, byte(isXfr), xfrRecType, "Second record should be isXfr")

	// isXfr RecSize should be 32 (8 hdr + 24 xfr stats)
	xfrRecSize := int(binary.BigEndian.Uint16(packet[xfrOffset+2 : xfrOffset+4]))
	assert.Equal(t, 32, xfrRecSize, "XFR RecSize should be 32")

	// Verify FileId
	xfrFileId := binary.BigEndian.Uint32(packet[xfrOffset+4 : xfrOffset+8])
	assert.Equal(t, uint32(300), xfrFileId, "FileId should match")

	// Verify Read bytes (offset +8 within xfr record, big-endian int64)
	readBytes := int64(binary.BigEndian.Uint64(packet[xfrOffset+8 : xfrOffset+16]))
	assert.Equal(t, int64(123456), readBytes, "Read bytes should match")

	// Verify Write bytes (offset +24 within xfr record, big-endian int64)
	writeBytes := int64(binary.BigEndian.Uint64(packet[xfrOffset+24 : xfrOffset+32]))
	assert.Equal(t, int64(789012), writeBytes, "Write bytes should match")
}

// TestAppInfoPacketRoundTrip verifies that an 'i' (appinfo) packet generated
// by the internal backend can be parsed by handlePacket and that the project
// is correctly extracted from the user agent string.
func TestAppInfoPacketRoundTrip(t *testing.T) {
	resetTestCaches(t)

	userId := uint32(201)
	xrdUserId := XrdUserId{
		Prot: "https",
		User: "appinfouser",
		Pid:  1,
		Sid:  66666,
		Host: "10.60.0.1",
	}
	event := TransferEvent{
		AuthProtocol: "https",
		UserDN:       "appinfouser",
		Role:         "user",
		UserAgent:    "�pelican-client/7.0.0 project/MyProject",
	}

	// First register the session via a 'u' packet so that userids cache is populated
	loginPacket, err := buildUserLoginPacket(1, userId, xrdUserId, event)
	require.NoError(t, err)
	err = handlePacket(loginPacket)
	require.NoError(t, err)

	// Build and parse the 'i' (appinfo) packet
	appInfoPacket, err := buildAppInfoPacket(2, userId, xrdUserId, event)
	require.NoError(t, err)
	require.NotEmpty(t, appInfoPacket)
	assert.Equal(t, byte('i'), appInfoPacket[0], "Packet code should be 'i'")

	err = handlePacket(appInfoPacket)
	require.NoError(t, err, "handlePacket should parse the appinfo packet")

	// The 'i' handler looks up xrdUserId in userids → gets userId → updates session with Project
	sessionItem := sessions.Get(UserId{Id: userId})
	require.NotNil(t, sessionItem, "Session should exist after 'i' packet")

	record := sessionItem.Value()
	assert.NotEmpty(t, record.Project, "Project should be extracted from user agent")
	assert.Equal(t, "MyProject", record.Project, "Project should match the one in user agent")

}

// TestDiscPacketRoundTrip verifies that an isDisc (disconnect) f-stream packet
// generated by the internal backend can be parsed by handlePacket and that it
// correctly removes the session from the sessions cache.
func TestDiscPacketRoundTrip(t *testing.T) {
	resetTestCaches(t)

	userId := uint32(202)
	xrdUserId := XrdUserId{
		Prot: "https",
		User: "discuser",
		Pid:  1,
		Sid:  77777,
		Host: "10.70.0.1",
	}
	event := TransferEvent{
		AuthProtocol: "https",
		UserDN:       "discuser",
	}

	// Register the session via a 'u' packet
	loginPacket, err := buildUserLoginPacket(1, userId, xrdUserId, event)
	require.NoError(t, err)
	err = handlePacket(loginPacket)
	require.NoError(t, err)

	// Verify session exists
	sessionItem := sessions.Get(UserId{Id: userId})
	require.NotNil(t, sessionItem, "Session should exist after login")

	// Build and parse the isDisc packet
	discPacket, err := buildFStreamDiscPacket(2, userId)
	require.NoError(t, err)
	require.NotEmpty(t, discPacket)
	assert.Equal(t, byte('f'), discPacket[0], "Disc packet code should be 'f'")

	err = handlePacket(discPacket)
	require.NoError(t, err, "handlePacket should parse the disconnect packet")

	// Verify the session was removed by isDisc
	sessionItem = sessions.Get(UserId{Id: userId})
	assert.Nil(t, sessionItem, "Session should be deleted after isDisc")

}
